import type { Metadata } from "next";
import { absoluteUrl, siteConfig } from "@/lib/site-config";

export const locales = ["es-BO", "en", "qu-BO"] as const;
export type Locale = (typeof locales)[number];

export const localeRoutes: Record<Locale, string> = {
  "es-BO": "/",
  en: "/en",
  "qu-BO": "/qu"
};

export const localeLabels: Record<Locale, { short: string; name: string }> = {
  "es-BO": { short: "ES", name: "Español" },
  en: { short: "EN", name: "English" },
  "qu-BO": { short: "QU", name: "Quechua" }
};

const es = {
  meta: {
    title: "AgroEscudo | Monitoreo inteligente para silos y almacenamiento de granos",
    description: "Tecnología boliviana de monitoreo postcosecha con sensores IoT, alertas, historial y reportes para silos, galpones, centros de acopio y granos almacenados.",
    ogDescription: "Sensores IoT, alertas, historial operativo y reportes para monitoreo postcosecha en Cochabamba y Santa Cruz, Bolivia."
  },
  nav: { product: "Solución", how: "Cómo funciona", platform: "Plataforma", agrotech: "AgroTECH", progress: "Avances", ecosystem: "Ecosistema", press: "Prensa", pilot: "Piloto", login: "Ingresar", cta: "Solicitar piloto", open: "Abrir menú", close: "Cerrar menú", home: "AgroEscudo inicio" },
  hero: {
    alt: "Visual conceptual fotorrealista de un silo y un nodo de monitoreo AgroEscudo",
    eyebrow: "Tecnología boliviana para proteger el valor del grano",
    title: "El grano no avisa. AgroEscudo sí.",
    copy: "Monitoreamos condiciones críticas en silos y centros de acopio para actuar antes de que el riesgo se convierta en pérdida.",
    note: "Instalación conceptual. La configuración final se define según cada sitio.",
    primary: "Solicitar un piloto", secondary: "Ver cómo funciona", tertiary: "Ingresar", microcopy: "Sensores IoT · Alertas · Historial · Bitácora · Reportes", location: "Preparación de pilotos en Cochabamba y Santa Cruz.",
    readings: [["Temperatura", "Lectura continua"], ["Humedad", "Umbral definido"], ["Estado", "Nodo conectado"]]
  },
  capabilities: { aria: "Capacidades desarrolladas", items: [["IoT", "Nodo funcional"], ["LoRa", "Comunicación probada"], ["Web + Android", "Producto MVP"], ["Bolivia", "Cochabamba y Santa Cruz"]] },
  problem: {
    eyebrow: "El riesgo invisible", title: "El problema no comienza cuando el grano se pierde.",
    copy: "Comienza cuando nadie puede ver a tiempo qué está pasando dentro del almacenamiento.",
    support: "Temperatura, humedad y tendencia convierten una inspección aislada en una decisión con evidencia.",
    visual: "Condiciones invisibles. Decisiones tardías. Sin historial.", signals: [["Temperatura", "Cambio térmico"], ["Humedad", "Condición ambiental"], ["Tendencia", "Evolución del riesgo"]]
  },
  solution: {
    eyebrow: "Sistema AgroEscudo", title: "Un sistema completo. No un sensor aislado.",
    copy: "El nodo registra variables críticas. La comunicación LoRa protege la continuidad del flujo y la plataforma convierte lecturas en información operativa que el equipo puede consultar y documentar.",
    items: [["Nodo", "Registra variables"], ["LoRa", "Transporta lecturas"], ["Gateway", "Concentra datos"], ["Plataforma", "Ordena el historial"], ["Alerta", "Activa respuesta"]],
    status: "Arquitectura MVP desarrollada para validación de campo.", flow: "Sensor → evidencia → decisión"
  },
  how: {
    eyebrow: "Cómo funciona", title: "Del grano a la alerta, sin puntos ciegos.",
    steps: [["Instalamos", "El nodo se adapta al sitio y registra variables acordadas con el operador."], ["Monitoreamos", "Las lecturas se guardan y transmiten periódicamente, incluso con conectividad intermitente."], ["Alertamos", "El sistema identifica condiciones fuera de los rangos configurados para el piloto."], ["Documentamos", "El historial, las alertas y las acciones quedan disponibles para seguimiento y reportes."]]
  },
  architecture: { aria: "Diagrama de la arquitectura AgroEscudo", alt: "Diagrama conceptual del sistema AgroEscudo: grano, sondas, LoRa, gateway, API, dashboard y alertas", caption: "Arquitectura conceptual del MVP. La cantidad y ubicación de sondas, así como la conectividad, dependen de cada instalación.", labels: { silo: "Silo + grano", probes: "Sondas internas", node: "SiloSensor", lora: "LoRa local", gateway: "Gateway", gatewayDetail: "Guarda y sincroniza", cloud: "Internet + API", cloudDetail: "Datos disponibles", platform: "Dashboard + app", platformDetail: "Alertas · historial · reportes", alert: "Alerta", grain: "Temperatura del grano", ambient: "Ambiente", connection: "Batería y conexión" }, items: [["SiloSensor", "Mide variables acordadas"], ["LoRa", "Comunicación local"], ["Gateway", "Almacena y sincroniza"], ["Internet + API", "Organiza las lecturas"], ["Plataforma", "Alertas, historial y reportes"]] },
  platform: {
    eyebrow: "Plataforma desarrollada", title: "Todos los datos. Una sola operación.", copy: "Condiciones actuales, alertas, historial y evidencia operativa para que el dato no se quede dentro del sensor.",
    items: ["Estado general", "Alertas", "Historial", "Reportes"], window: "Plataforma AgroEscudo · vista demostrativa",
    alt: "Vista real de la plataforma AgroEscudo con estado operativo, alertas e indicadores", note: "Captura del MVP existente con información demostrativa.", login: "Ingresar a la plataforma", demo: "Solicitar una demostración"
  },
  credibility: { press: "Presentado en La Razón", ecosystem: "Acompañamiento institucional", technology: "MVP IoT desarrollado", local: "Tecnología boliviana" },
  product: { eyebrow: "Solución", title: "Medir. Detectar. Actuar.", copy: "Un sistema completo para convertir señales del almacenamiento en acciones operativas.", items: [["Monitoreo", "Lecturas continuas de las variables definidas para el sitio."], ["Alertas", "Avisos configurables cuando una condición sale de rango."], ["Historial y bitácora", "Eventos y acciones reunidos en una fuente compartida."], ["Reportes", "Evidencia clara para seguimiento técnico y operativo."]] },
  why: { eyebrow: "Por qué AgroEscudo", title: "Diseñado para operar en el contexto real de Bolivia.", items: [["Tecnología local", "Desarrollo cercano a la realidad de almacenamiento y postcosecha del país."], ["Conectividad intermitente", "La arquitectura contempla guardar y sincronizar lecturas cuando vuelve la conexión."], ["Enfoque B2B", "Pensado para responsables de inventario, calidad y continuidad operativa."]] },
  agrotech: { eyebrow: "AgroTECH Bolivia 2026", title: "Tecnología postcosecha en conversación con el sector.", copy: "AgroEscudo participó en espacios públicos de innovación agrícola. La galería se publicará cuando contemos con fotografías originales autorizadas.", link: "Ver cobertura pública" },
  progress: {
    eyebrow: "Avances verificables", title: "Del prototipo a una operación piloto.", copy: "Mostramos la etapa de cada componente tal como es hoy. La siguiente prueba relevante es conectar la tecnología desarrollada con condiciones reales de almacenamiento.",
    items: [["Nodo y comunicación LoRa", "Probado en laboratorio"], ["API y almacenamiento de lecturas", "Desarrollado"], ["Dashboard web", "Desplegado"], ["Aplicación Android", "Versión MVP"], ["Recuperación ante desconexión", "En validación"], ["Instalación en operación real", "Próximo piloto"]]
  },
  founder: {
    role: "Fundador y CEO", location: "Cochabamba · Bolivia", alt: "Brayan Javier Mejía Saavedra, fundador y CEO de AgroEscudo",
    lead: "Lidera la construcción y validación de AgroEscudo, conectando tecnología IoT con necesidades reales de almacenamiento y postcosecha.",
    copy: "Su trabajo integra visión de producto, desarrollo tecnológico y preparación de pilotos para convertir datos de silos y galpones en decisiones operativas más oportunas.",
    principle: "Principio de trabajo", quote: "Tecnología útil, evidencia operativa y validación en campo.", contact: "Conversar con Brayan", interview: "Leer entrevista en La Razón"
  },
  ecosystem: {
    eyebrowTop: "Ecosistema institucional", headline: "Respaldados por un ecosistema que impulsa la innovación boliviana.", eyebrow: "Organizaciones que nos respaldan", title: "Apoyo real para avanzar con más rigor.",
    copy: "AgroEscudo fortalece su desarrollo tecnológico, comercial y académico con el respaldo de organizaciones bolivianas vinculadas a la innovación, la incubación empresarial y la formación técnica.",
    categories: ["Preaceleración", "Incubación tecnológica", "Respaldo académico", "Acompañamiento técnico"],
    descriptions: ["Fortalecimiento empresarial y preparación para conectar la solución con el mercado.", "Articulación dentro del ecosistema de innovación y preaceleración empresarial.", "Respaldo institucional vinculado al proceso de fortalecimiento empresarial de Innova Up.", "Acompañamiento para estructuración, incubación y desarrollo de la empresa tecnológica.", "Acompañamiento académico al desarrollo tecnológico del equipo fundador.", "Entorno académico vinculado a EMBATE y a la articulación técnica del proyecto.", "Articulación técnica para fortalecer la validación aplicada en el sector agrícola."],
    disclaimer: "El respaldo corresponde a procesos de acompañamiento, incubación, preaceleración y articulación institucional; no implica inversión, certificación ni relación comercial."
  },
  clients: {
    eyebrow: "Para quién es", title: "Para operaciones donde conocer tarde cuesta más.", riskLabel: "Riesgo operativo", decisionLabel: "Decisión que mejora",
    items: [["Protección de inventario", "Silos · galpones · centros de acopio", "Inventario concentrado expuesto a cambios que una ronda ocasional puede no revelar.", "Priorizar inspección, ventilación o seguimiento según evidencia."], ["Continuidad operativa", "Molinos · alimentos balanceados · agroindustria", "Una condición fuera de rango puede afectar recepción, almacenamiento y programación de planta.", "Coordinar respuesta antes de que el evento comprometa el proceso siguiente."], ["Supervisión y trazabilidad", "Cooperativas · calidad · administradores multisitio", "Sin historial común, comparar sitios y justificar acciones consume tiempo operativo.", "Revisar eventos, responsables y acciones desde una fuente compartida."]]
  },
  press: {
    eyebrow: "Prensa, reconocimientos y cobertura", title: "AgroEscudo en el ecosistema de innovación.", copy: "Cobertura, reconocimiento y participación pública de una tecnología boliviana enfocada en reducir el riesgo postcosecha con monitoreo de silos, galpones y centros de acopio.",
    cover: "Portada del suplemento", article: "Entrevista publicada", evidence: "Evidencia editorial", sourceNote: "Ver la publicación en su fuente original.", open: "Abrir fuente", more: "Más cobertura indexable de AgroEscudo", moreCopy: "Prensa, reconocimientos y participación pública, separados de clientes, inversión o certificaciones.", moreLink: "Ver página de prensa", readAria: "Leer cobertura de AgroEscudo en"
  },
  pilot: {
    eyebrow: "Próximo piloto", title: "Tu instalación puede ser el próximo piloto AgroEscudo.", copy: "Buscamos operaciones de almacenamiento, acopio y transformación en Cochabamba y Santa Cruz para validar el sistema en condiciones reales y medir disponibilidad, eventos detectados y tiempos de respuesta.",
    location: "Cochabamba · Santa Cruz", primary: "Solicitar evaluación del sitio", secondary: "Hablar por WhatsApp", note: "La evaluación confirma si el caso tiene sentido operativo. No implica piloto gratuito ni compromiso de compra.", route: "Ruta de validación", stages: ["Evaluación inicial del sitio", "Definición de variables y umbrales", "Instalación y monitoreo", "Informe de resultados"], observe: "Qué se observa", metrics: ["Disponibilidad del sistema", "Eventos detectados", "Tiempo de respuesta", "Acciones registradas"]
  },
  faq: {
    eyebrow: "Preguntas frecuentes", title: "Lo básico para evaluar AgroEscudo sin vueltas.", copy: "Respuestas directas para operadores que están considerando monitoreo de silos, granos almacenados e IoT agrícola en Bolivia.",
    items: [["¿Qué monitorea AgroEscudo?", "AgroEscudo monitorea temperatura y humedad en silos, galpones y centros de acopio para detectar condiciones de riesgo postcosecha y apoyar decisiones operativas."], ["¿AgroEscudo funciona sin internet permanente?", "El piloto se diseña considerando conectividad variable. La arquitectura contempla operación en campo y seguimiento de lecturas para no depender de una conexión ideal."], ["¿Dónde puede instalarse?", "Puede evaluarse en silos, galpones, centros de acopio, molinos, cooperativas, plantas de alimentos balanceados y agroindustrias con inventario agrícola almacenado."], ["¿Está disponible en Cochabamba y Santa Cruz?", "Sí. La primera etapa de validación comercial prioriza instalaciones piloto en Cochabamba y Santa Cruz, Bolivia."], ["¿Cómo se solicita un piloto?", "El primer paso es escribir por WhatsApp para coordinar una revisión del sitio. Con esa información se define si el caso operativo merece un piloto de 60 a 90 días."], ["¿AgroEscudo reemplaza el manejo técnico del silo?", "No. AgroEscudo no reemplaza la experiencia del operador. Aporta datos, alertas, historial y evidencia para apoyar decisiones de manejo."], ["¿Los sensores se venden o se entregan como servicio?", "En esta etapa se prioriza el piloto operativo. El modelo final se define según el sitio, los nodos requeridos, el acompañamiento y la necesidad de reportes."], ["¿Qué tipo de operaciones pueden evaluar AgroEscudo?", "AgroEscudo está pensado para operaciones con granos almacenados, inventario agrícola, silos, galpones, plantas, centros de acopio y agroindustrias que necesitan visibilidad y trazabilidad."]]
  },
  cta: { eyebrow: "Contacto directo", title: "¿Tienes grano almacenado y necesitas mayor visibilidad?", copy: "Conversemos sobre tu sitio, las variables críticas y el alcance de un posible piloto.", location: "Cochabamba y Santa Cruz, Bolivia", email: "Correo" },
  footer: { description: "AgroEscudo desarrolla tecnología de monitoreo para reducir riesgos operativos y postcosecha en silos, galpones y centros de acopio.", navigation: "Navegación", contact: "Contacto", location: "Operación inicial en Cochabamba y Santa Cruz, Bolivia.", rights: "Todos los derechos reservados.", tagline: "Monitoreo inteligente para proteger granos almacenados.", fullPress: "Cobertura completa" },
  whatsapp: "Hablar con AgroEscudo"
};

const en: typeof es = {
  meta: { title: "AgroEscudo | Smart monitoring for silos and stored grain", description: "Bolivian post-harvest monitoring technology combining IoT sensors, alerts, operational history, and reports for silos and grain storage facilities.", ogDescription: "IoT sensors, alerts, operational history, and reports for post-harvest monitoring in Cochabamba and Santa Cruz, Bolivia." },
  nav: { product: "Solution", how: "How it works", platform: "Platform", agrotech: "AgroTECH", progress: "Progress", ecosystem: "Ecosystem", press: "Press", pilot: "Pilot", login: "Sign in", cta: "Request a pilot", open: "Open menu", close: "Close menu", home: "AgroEscudo home" },
  hero: { alt: "Photorealistic conceptual view of a grain silo and AgroEscudo monitoring node", eyebrow: "Bolivian technology protecting the value of grain", title: "Grain does not warn you. AgroEscudo does.", copy: "We monitor critical conditions in silos and collection facilities so teams can act before risk becomes loss.", note: "Conceptual installation. Final configuration depends on each site.", primary: "Request a pilot", secondary: "See how it works", tertiary: "Sign in", microcopy: "IoT sensors · Alerts · History · Logbook · Reports", location: "Pilot preparation in Cochabamba and Santa Cruz.", readings: [["Temperature", "Continuous reading"], ["Humidity", "Defined threshold"], ["Status", "Node connected"]] },
  capabilities: { aria: "Developed capabilities", items: [["IoT", "Functional node"], ["LoRa", "Tested communication"], ["Web + Android", "MVP product"], ["Bolivia", "Cochabamba and Santa Cruz"]] },
  problem: { eyebrow: "The invisible risk", title: "The problem does not begin when grain is lost.", copy: "It begins when no one can see what is happening inside storage in time.", support: "Temperature, humidity, and trend turn an isolated inspection into an evidence-based decision.", visual: "Invisible conditions. Late decisions. No history.", signals: [["Temperature", "Thermal change"], ["Humidity", "Environmental condition"], ["Trend", "Risk evolution"]] },
  solution: { eyebrow: "AgroEscudo system", title: "A complete system. Not an isolated sensor.", copy: "The node records critical variables. LoRa communication supports data continuity, while the platform turns readings into operational information the team can review and document.", items: [["Node", "Records variables"], ["LoRa", "Transmits readings"], ["Gateway", "Concentrates data"], ["Platform", "Organizes history"], ["Alert", "Triggers response"]], status: "MVP architecture developed for field validation.", flow: "Sensor → evidence → decision" },
  how: { eyebrow: "How it works", title: "From grain to alert, without blind spots.", steps: [["We install", "The node is adapted to the site and records variables agreed with the operator."], ["We monitor", "Readings are stored and transmitted periodically, even with intermittent connectivity."], ["We alert", "The system identifies conditions outside the thresholds configured for the pilot."], ["We document", "History, alerts, and actions remain available for follow-up and reports."]] },
  architecture: { aria: "AgroEscudo architecture diagram", alt: "Conceptual AgroEscudo system diagram: grain, probes, LoRa, gateway, API, dashboard, and alerts", caption: "Conceptual MVP architecture. Probe count and placement, as well as connectivity, depend on each facility.", labels: { silo: "Silo + grain", probes: "Internal probes", node: "SiloSensor", lora: "Local LoRa", gateway: "Gateway", gatewayDetail: "Stores and syncs", cloud: "Internet + API", cloudDetail: "Data available", platform: "Dashboard + app", platformDetail: "Alerts · history · reports", alert: "Alert", grain: "Grain temperature", ambient: "Environment", connection: "Battery and connection" }, items: [["SiloSensor", "Measures agreed variables"], ["LoRa", "Local communication"], ["Gateway", "Stores and synchronizes"], ["Internet + API", "Organizes readings"], ["Platform", "Alerts, history, and reports"]] },
  platform: { eyebrow: "Platform developed", title: "All the data. One operation.", copy: "Current conditions, alerts, history, and operational evidence so data does not remain trapped inside the sensor.", items: ["Overall status", "Alerts", "History", "Reports"], window: "AgroEscudo platform · demonstration view", alt: "AgroEscudo platform showing operational status, alerts, and indicators", note: "Screenshot of the existing MVP with demonstration data.", login: "Sign in to the platform", demo: "Request a demonstration" },
  credibility: { press: "Featured in La Razón", ecosystem: "Institutional support", technology: "IoT MVP developed", local: "Bolivian technology" },
  product: { eyebrow: "Solution", title: "Measure. Detect. Act.", copy: "A complete system that turns storage signals into operational action.", items: [["Monitoring", "Continuous readings of the variables defined for the site."], ["Alerts", "Configurable notices when a condition moves out of range."], ["History and logbook", "Events and actions brought together in one shared source."], ["Reports", "Clear evidence for technical and operational follow-up."]] },
  why: { eyebrow: "Why AgroEscudo", title: "Designed for Bolivia's operating reality.", items: [["Local technology", "Development close to the country's storage and post-harvest context."], ["Intermittent connectivity", "The architecture can store and synchronize readings when connectivity returns."], ["B2B focus", "Built for inventory, quality, and operational continuity teams."]] },
  agrotech: { eyebrow: "AgroTECH Bolivia 2026", title: "Post-harvest technology in conversation with the industry.", copy: "AgroEscudo has participated in public agricultural innovation spaces. The gallery will be published when authorized original photographs are available.", link: "View public coverage" },
  progress: { eyebrow: "Verifiable progress", title: "From prototype to a pilot operation.", copy: "We show each component's current stage as it is today. The next relevant test is connecting the developed technology with real storage conditions.", items: [["Node and LoRa communication", "Laboratory tested"], ["API and reading storage", "Developed"], ["Web dashboard", "Deployed"], ["Android application", "MVP version"], ["Disconnection recovery", "Under validation"], ["Installation in a real operation", "Next pilot"]] },
  founder: { role: "Founder and CEO", location: "Cochabamba · Bolivia", alt: "Brayan Javier Mejía Saavedra, founder and CEO of AgroEscudo", lead: "He leads the development and validation of AgroEscudo, connecting IoT technology with real storage and post-harvest needs.", copy: "His work combines product vision, technology development, and pilot preparation to turn silo and warehouse data into more timely operational decisions.", principle: "Working principle", quote: "Useful technology, operational evidence, and field validation.", contact: "Talk with Brayan", interview: "Read the La Razón interview" },
  ecosystem: { eyebrowTop: "Institutional ecosystem", headline: "Supported by an ecosystem advancing Bolivian innovation.", eyebrow: "Organizations supporting us", title: "Real support to move forward with greater rigor.", copy: "AgroEscudo strengthens its technological, commercial, and academic development with support from Bolivian organizations connected to innovation, business incubation, and technical education.", categories: ["Pre-acceleration", "Technology incubation", "Academic support", "Technical support"], descriptions: ["Business strengthening and preparation to connect the solution with the market.", "Connection within the innovation ecosystem and business pre-acceleration.", "Institutional support linked to the Innova Up business strengthening process.", "Support for structuring, incubating, and developing the technology venture.", "Academic support for the founding team's technology development.", "Academic environment connected to EMBATE and the project's technical coordination.", "Technical coordination to strengthen applied validation in the agricultural sector."], disclaimer: "Support refers to mentoring, incubation, pre-acceleration, and institutional coordination processes; it does not imply investment, certification, or a commercial relationship." },
  clients: { eyebrow: "Who it is for", title: "For operations where learning late costs more.", riskLabel: "Operational risk", decisionLabel: "Decision improved", items: [["Inventory protection", "Silos · warehouses · grain collection facilities", "Concentrated inventory exposed to changes that an occasional inspection may not reveal.", "Prioritize inspection, ventilation, or follow-up based on evidence."], ["Operational continuity", "Mills · feed plants · agribusiness", "An out-of-range condition may affect reception, storage, and plant scheduling.", "Coordinate a response before the event compromises the next process."], ["Supervision and traceability", "Cooperatives · quality teams · multi-site managers", "Without shared history, comparing sites and justifying actions consumes operational time.", "Review events, responsible teams, and actions from one shared source."]] },
  press: { eyebrow: "Press, recognition, and coverage", title: "AgroEscudo in the innovation ecosystem.", copy: "Coverage, recognition, and public participation of a Bolivian technology focused on reducing post-harvest risk through silo, warehouse, and grain collection monitoring.", cover: "Supplement cover", article: "Published interview", evidence: "Editorial evidence", sourceNote: "View the publication at its original source.", open: "Open source", more: "More indexable coverage of AgroEscudo", moreCopy: "Press, recognition, and public participation, clearly separated from customers, investment, or certifications.", moreLink: "View press page", readAria: "Read AgroEscudo coverage in" },
  pilot: { eyebrow: "Next pilot", title: "Your facility could be the next AgroEscudo pilot.", copy: "We are looking for storage, collection, and processing operations in Cochabamba and Santa Cruz to validate the system under real conditions and measure availability, detected events, and response times.", location: "Cochabamba · Santa Cruz", primary: "Request a site assessment", secondary: "Talk on WhatsApp", note: "The assessment confirms whether the use case makes operational sense. It does not imply a free pilot or purchase commitment.", route: "Validation path", stages: ["Initial site assessment", "Definition of variables and thresholds", "Installation and monitoring", "Results report"], observe: "What is observed", metrics: ["System availability", "Detected events", "Response time", "Recorded actions"] },
  faq: { eyebrow: "Frequently asked questions", title: "The essentials for evaluating AgroEscudo.", copy: "Direct answers for operators considering silo monitoring, stored grain, and agricultural IoT in Bolivia.", items: [["What does AgroEscudo monitor?", "AgroEscudo monitors temperature and humidity in silos, warehouses, and collection facilities to identify post-harvest risk conditions and support operational decisions."], ["Does AgroEscudo work without permanent internet?", "The pilot is designed for variable connectivity. The architecture considers field operation and reading continuity without depending on an ideal connection."], ["Where can it be installed?", "It can be assessed for silos, warehouses, collection facilities, mills, cooperatives, feed plants, and agribusinesses with stored agricultural inventory."], ["Is it available in Cochabamba and Santa Cruz?", "Yes. The first commercial validation stage prioritizes pilot facilities in Cochabamba and Santa Cruz, Bolivia."], ["How can I request a pilot?", "The first step is to contact us on WhatsApp to coordinate a site review. This information helps determine whether the operational case merits a 60 to 90 day pilot."], ["Does AgroEscudo replace technical silo management?", "No. AgroEscudo does not replace operator experience. It provides data, alerts, history, and evidence to support management decisions."], ["Are sensors sold or provided as a service?", "At this stage, the operational pilot is the priority. The final model depends on the site, required nodes, support, and reporting needs."], ["What kinds of operations can evaluate AgroEscudo?", "AgroEscudo is designed for operations with stored grain, agricultural inventory, silos, warehouses, plants, collection facilities, and agribusinesses that need visibility and traceability."]] },
  cta: { eyebrow: "Direct contact", title: "Do you store grain and need greater visibility?", copy: "Let us discuss your facility, its critical variables, and the scope of a possible pilot.", location: "Cochabamba and Santa Cruz, Bolivia", email: "Email" },
  footer: { description: "AgroEscudo develops monitoring technology to reduce operational and post-harvest risks in silos, warehouses, and grain collection facilities.", navigation: "Navigation", contact: "Contact", location: "Initial operations in Cochabamba and Santa Cruz, Bolivia.", rights: "All rights reserved.", tagline: "Smart monitoring to protect stored grain.", fullPress: "Full coverage" },
  whatsapp: "Talk with AgroEscudo"
};

const qu: typeof es = {
  meta: { title: "AgroEscudo | Silokunapi waqaychasqa granupaq monitoreo", description: "Boliviapi ruwasqa postcosecha monitoreo: IoT sensores, alertas, historial chaymanta reportes silokunapaq, galponkunapaq, acopio wasikunapaq.", ogDescription: "IoT sensores, alertas chaymanta reportes Cochabamba, Santa Cruzpi waqaychasqa granuta qhawarinapaq." },
  nav: { product: "Sistema", how: "Imayna llamk'an", platform: "Plataforma", agrotech: "AgroTECH", progress: "Ñawpaqman risqanchik", ecosystem: "Yanapakuqkuna", press: "Willakuykuna", pilot: "Piloto", login: "Yaykuy", cta: "Piloto mañay", open: "Menú kichariy", close: "Menú wichq'ay", home: "AgroEscudo qallariy" },
  hero: { alt: "Silo chaymanta AgroEscudo monitoreo nodopa conceptual rikch'aynin", eyebrow: "Boliviapi ruwasqa tecnología, granu waqaychanapaq", title: "Granu mana willanchu. AgroEscudoqa willan.", copy: "Silokunapi chaymanta acopio wasikunapi condición importantekunata qhawariyku, riesgo chinkayman mana tukuchkaptin ruwanapaq.", note: "Kayqa conceptual instalaciónmi. Sapa sitioqa wakin configuraciónta munan.", primary: "Piloto mañay", secondary: "Imayna llamk'an", tertiary: "Yaykuy", microcopy: "IoT sensores · Alertas · Historial · Bitácora · Reportes", location: "Cochabamba, Santa Cruzpi pilotokuna wakichisqa.", readings: [["Temperatura", "Sapa kuti ñawirisqa"], ["Humedad", "Umbral churarisqa"], ["Estado", "Nodo tinkisqa"]] },
  capabilities: { aria: "Ruwasqa atiyninkuna", items: [["IoT", "Nodo llamk'achkan"], ["LoRa", "Comunicación yachasqa"], ["Web + Android", "MVP producto"], ["Bolivia", "Cochabamba chaymanta Santa Cruz"]] },
  problem: { eyebrow: "Mana rikukuq riesgo", title: "Problemaqa mana granu chinkaptin qallarinchu.", copy: "Waqaychana ukhupi imapas ruwachkaptin mana pachanpi rikuy atiptinmi qallarin.", support: "Temperatura, humedad chaymanta tendenciaqa evidenciawan decisiónta yanapan.", visual: "Mana rikukuq condiciones. Qhipa decisiones. Mana historial.", signals: [["Temperatura", "Q'uñi tikray"], ["Humedad", "Pachapa condiciónnin"], ["Tendencia", "Riesgopa puriynin"]] },
  solution: { eyebrow: "AgroEscudo sistema", title: "Hunt'a sistema. Mana sapallan sensorchu.", copy: "Nodo variables importantes nisqata qillqan. LoRa comunicación datokunata apachin, plataformañataq historialpi wakichin, equipo qhawanampaq chaymanta qillqanampaq.", items: [["Nodo", "Variables qillqan"], ["LoRa", "Lecturas apachin"], ["Gateway", "Datokuna huñun"], ["Plataforma", "Historial wakichin"], ["Alerta", "Kutichiyta qallarin"]], status: "MVP arquitectura campopi validanapaq ruwasqa.", flow: "Sensor → evidencia → decisión" },
  how: { eyebrow: "Imayna llamk'an", title: "Granumanta alertakama, mana chinkaspa.", steps: [["Churayku", "Nodoqa cheqasman wakichisqa, operadorwan variables akllasqata qillqan."], ["Qhawariyku", "Lecturakuna waqaychasqa chaymanta sapa kuti apachisqa, internet pisi kaptinpas."], ["Alertayku", "Sistemaqa piloto umbralninkunamanta lluqsisqa condiciónkunata tarin."], ["Qillqayku", "Historial, alertas chaymanta acciones qhawanapaq reportekunapipas kanku."]] },
  architecture: { aria: "AgroEscudo arquitectura diagrama", alt: "AgroEscudo sistema diagrama: granu, sondas, LoRa, gateway, API, dashboard chaymanta alertas", caption: "MVP conceptual arquitectura. Sondakuna, tupuna cheqakuna chaymanta conectividad sapa instalaciónman hina akllakun.", labels: { silo: "Silo + granu", probes: "Ukhu sondakuna", node: "SiloSensor", lora: "LoRa local", gateway: "Gateway", gatewayDetail: "Waqaychan, sincronizan", cloud: "Internet + API", cloudDetail: "Datos kachkan", platform: "Dashboard + app", platformDetail: "Alertas · historial · reportes", alert: "Alerta", grain: "Granu temperatura", ambient: "Pacha", connection: "Batería, conexión" }, items: [["SiloSensor", "Akllasqa variables tupun"], ["LoRa", "Cheqapi comunicación"], ["Gateway", "Waqaychan chaymanta sincronizan"], ["Internet + API", "Lecturakuna wakichin"], ["Plataforma", "Alertas, historial chaymanta reportes"]] },
  platform: { eyebrow: "Plataforma ruwasqa", title: "Llapan datos. Huk operación.", copy: "Kunan condiciónkuna, alertakuna, historial chaymanta evidencia operativa, dato mana sensor ukhullapi qhipananpaq.", items: ["Estado general", "Alertas", "Historial", "Reportes"], window: "AgroEscudo plataforma · demostración", alt: "AgroEscudo plataforma, estado, alertas chaymanta indicadoreswan", note: "MVP ruwasqapa captura, demostración datokunawan.", login: "Plataformaman yaykuy", demo: "Demostración mañay" },
  credibility: { press: "La Razónpi rikuchisqa", ecosystem: "Institución yanapay", technology: "IoT MVP ruwasqa", local: "Bolivia tecnología" },
  product: { eyebrow: "Sistema", title: "Tupuy. Tariy. Ruway.", copy: "Waqaychana señalkunata operación ruwayman tukuchiq hunt'a sistema.", items: [["Monitoreo", "Sitiopaq akllasqa variables sapa kuti ñawirisqa."], ["Alertas", "Condición umbralmanta lluqsiptin willakuy."], ["Historial, bitácora", "Eventokuna chaymanta acciones huk fuentepi."], ["Reportes", "Técnico chaymanta operación qatiypaq evidencia."]] },
  why: { eyebrow: "Imarayku AgroEscudo", title: "Boliviapa chiqaq operaciónninpaq ruwasqa.", items: [["Local tecnología", "Bolivia waqaychana chaymanta postcosecha realidadninman asuykusqa."], ["Internet pisi kaptin", "Conexión kutimuptin lecturakuna waqaychaspa sincronizan."], ["B2B enfoque", "Inventario, calidad chaymanta operación equipokunapaq ruwasqa."]] },
  agrotech: { eyebrow: "AgroTECH Bolivia 2026", title: "Postcosecha tecnología sectorwan riman.", copy: "AgroEscudoqa agricultura innovación espacios públicospi participasqa. Original autorizasqa fotografíakuna kaptin galería publicakunqa.", link: "Cobertura qhaway" },
  progress: { eyebrow: "Rikuchiy atina ñawpaqman risqa", title: "Prototipomanta piloto operaciónkama.", copy: "Sapa componentepa kunan estado-ninta chiqaqta rikuchiyku. Qatiq pruebaqa ruwasqa tecnologíata waqaychana cheqapi tinkichiymi.", items: [["Nodo chaymanta LoRa comunicación", "Laboratoriopi yachasqa"], ["API chaymanta lecturas waqaychay", "Ruwasqa"], ["Web dashboard", "Publicasqa"], ["Android aplicación", "MVP versión"], ["Mana conexión kaptin kutichiy", "Validaciónpi"], ["Operación realpi churay", "Qatiq piloto"]] },
  founder: { role: "Fundador chaymanta CEO", location: "Cochabamba · Bolivia", alt: "Brayan Javier Mejía Saavedra, AgroEscudopa fundador chaymanta CEO", lead: "AgroEscudota ruwan chaymanta validan, IoT tecnologíata waqaychana postcosecha necesitadkunawan tinkichispa.", copy: "Paypa llamk'ayninqa producto yuyayta, tecnología ruwayta chaymanta pilotokuna wakichiyta huñun, silo galpón datokunata pachanpi decisiónman tukuchinapaq.", principle: "Llamk'ana kamachi", quote: "Allin tecnología, evidencia operativa chaymanta campopi validación.", contact: "Brayanwan rimay", interview: "La Razón entrevistata ñawiriy" },
  ecosystem: { eyebrowTop: "Institución yanapakuqkuna", headline: "Bolivia innovaciónta wiñachiq organizacioneswan yanapasqa.", eyebrow: "Yanapawaqniyku organizaciones", title: "Aswan allinta purinapaq chiqaq yanapay.", copy: "AgroEscudo tecnología, negocio chaymanta academia wiñayninta Bolivia organizacioneswan kallpachan; paykuna innovación, incubación chaymanta formación técnicawan llamk'anku.", categories: ["Preaceleración", "Tecnología incubación", "Academia yanapay", "Técnico yanapay"], descriptions: ["Negociota kallpachay chaymanta mercadoman yaykunapaq wakichiy.", "Innovación ecosistemapi chaymanta preaceleraciónpi tinkichiy.", "Innova Up empresata kallpachana procesopi institución yanapay.", "Tecnología empresata wakichiy, incubay chaymanta wiñachiy.", "Fundador equipopa tecnología ruwananpaq academia yanapay.", "EMBATEwan chaymanta proyectopa técnico articulaciónninwan tinkisqa academia.", "Agricultura sectorpi validación aplicada kallpachanapaq técnico articulación."], disclaimer: "Kay yanapayqa acompañamiento, incubación, preaceleración chaymanta institución articulación procesokunamanta; mana inversión, certificación nita comercial relación niyku." },
  clients: { eyebrow: "Pipaq", title: "Qhipata yachayqa aswan achkha chanin operacionespaq.", riskLabel: "Operación riesgo", decisionLabel: "Allin decisión", items: [["Inventario waqaychay", "Silos · galpones · acopio wasikuna", "Huñusqa inventarioqa tikrakuykunaman kichasqa, wakin kuti qhawasqalla mana rikunmanchu.", "Evidenciwan inspección, ventilación utaq qatiyta ñawpaqman churay."], ["Operación mana sayanapaq", "Molinos · alimentos balanceados · agroindustria", "Umbralmanta lluqsisqa condiciónqa recepción, almacenamiento chaymanta planta programaciónta wakllichinman.", "Qatiq proceso mana wakllichkaptin kutichiyta wakichiy."], ["Qhawariy chaymanta trazabilidad", "Cooperativas · calidad · achkha sitio kamachiqkuna", "Huk historial mana kaptin, sitiokunata tupachiy chaymanta acciones sut'inchay pacha apakun.", "Eventokunata, responsables chaymanta acciones huk fuentemanta qhaway."]] },
  press: { eyebrow: "Willakuy, reconocimiento chaymanta cobertura", title: "AgroEscudo innovación ukhupi.", copy: "Boliviapi ruwasqa tecnología postcosecha riesguta pisiyachinapaq silokunata, galponkunata chaymanta acopio wasikunata qhawarisqan manta willakuykuna.", cover: "Suplementopa portada", article: "Publicasqa entrevista", evidence: "Prensa evidencia", sourceNote: "Qallariy fuentepi publicaciónta qhaway.", open: "Fuente qhaway", more: "AgroEscudomanta aswan willakuy", moreCopy: "Prensa, reconocimiento chaymanta participación; mana clientes, inversión nita certificaciónchu.", moreLink: "Prensa p'anqata qhaway", readAria: "AgroEscudo coberturata kaypi ñawiriy" },
  pilot: { eyebrow: "Qatiq piloto", title: "Qampa instalaciónniyki AgroEscudopa qatiq piloton kanman.", copy: "Cochabamba, Santa Cruzpi almacenamiento, acopio chaymanta transformación operaciones mask'ayku, sistema real condiciónkunapi validanapaq chaymanta disponibilidad, eventokuna, kutichiy pacha tupunapaq.", location: "Cochabamba · Santa Cruz", primary: "Sitio evaluación mañay", secondary: "WhatsAppwan rimay", note: "Evaluaciónqa kay casoq operacionpaq allin kasqanta qhawan. Mana gratuito piloto nita ranti compromisochu.", route: "Validación ñan", stages: ["Sitio qallariy evaluación", "Variables chaymanta umbrales akllay", "Churay chaymanta monitoreo", "Resultados reporte"], observe: "Imata qhawasqa", metrics: ["Sistema disponibilidad", "Taripasqa eventokuna", "Kutichiy pacha", "Qillqasqa acciones"] },
  faq: { eyebrow: "Sapa kuti tapuykuna", title: "AgroEscudota qhawanapaq yachanapaq.", copy: "Boliviapi silo monitoreo, waqaychasqa granu chaymanta IoT agrícola qhawachkaq operadorespaq sut'i kutichiykuna.", items: [["¿Imata AgroEscudo qhawarin?", "AgroEscudo silokunapi, galponkunapi, acopio wasikunapi temperatura chaymanta humedadta qhawarin, postcosecha riesgo condiciónkunata tarinapaq chaymanta decisiónta yanapanapaq."], ["¿Internet sapa kuti mana kaptin AgroEscudo llamk'anchu?", "Pilotoqa internet tikrakuq kasqanman hina ruwasqa. Arquitecturaqa campopi llamk'ayta chaymanta lecturakuna qatiyta yuyarin, allin conexiónllamanta mana hap'ipakunachu."], ["¿Maypi churakunman?", "Silokunapi, galponkunapi, acopio wasikunapi, molinospi, cooperativakunapi chaymanta agroindustriakunapi qhawakunman."], ["¿Cochabamba, Santa Cruzpi kachkanchu?", "Arí. Qallariy validación comercialqa Cochabamba, Santa Cruzpi piloto instalaciones ñawpaqman churan."], ["¿Imayna piloto mañakun?", "Ñawpaqta WhatsAppwan qillqay, sitio qhawariyta wakichinapaq. Chay willakuywan casoq piloto merecen chayta akllakun."], ["¿AgroEscudo silo técnico manejota qhechunchu?", "Mana. AgroEscudoqa operadorpa yachayninta mana qhechunchu. Datos, alertas, historial chaymanta evidenciawan decisiónta yanapan."], ["¿Sensores rantikunchu utaq serviciopi qukunchu?", "Kunanqa piloto operativo ñawpaqpi kachkan. Modeloqa sitio, nodokuna, acompañamiento chaymanta reportes necesitadman hina akllakun."], ["¿Ima operaciones AgroEscudota qhawankuman?", "Waqaychasqa granuyuq, siloyuq, galponniyuq, plantayuq, acopio wasiyuq chaymanta agroindustria operacionespaq ruwasqa."]] },
  cta: { eyebrow: "Chiqaq contacto", title: "Waqaychasqa granuyki kachkanchu, aswan rikuyta munankichu?", copy: "Sitioymanta, variables importantesmanta chaymanta posible pilotomanta rimasun.", location: "Cochabamba chaymanta Santa Cruz, Bolivia", email: "Correo" },
  footer: { description: "AgroEscudo silokunapi, galponkunapi, acopio wasikunapi riesgo operativo chaymanta postcosecha pisiyachinapaq monitoreo tecnologíata ruwan.", navigation: "Navegación", contact: "Contacto", location: "Qallariy operación Cochabamba, Santa Cruz, Boliviapi.", rights: "Llapan derechokuna waqaychasqa.", tagline: "Waqaychasqa granuta waqaychanapaq monitoreo inteligente.", fullPress: "Llapan cobertura" },
  whatsapp: "AgroEscudowan rimay"
};

export const messages: Record<Locale, typeof es> = { "es-BO": es, en, "qu-BO": qu };

export function getMessages(locale: Locale) {
  return messages[locale];
}

export function getLocaleMetadata(locale: Locale): Metadata {
  const content = messages[locale].meta;
  const route = localeRoutes[locale];
  return {
    title: content.title,
    description: content.description,
    keywords: [...siteConfig.keywords],
    alternates: {
      canonical: route,
      languages: {
        "es-BO": "/",
        en: "/en",
        "qu-BO": "/qu",
        "x-default": "/"
      }
    },
    openGraph: {
      title: content.title,
      description: content.ogDescription,
      url: absoluteUrl(route),
      siteName: siteConfig.name,
      locale: locale.replace("-", "_"),
      alternateLocale: locales.filter((item) => item !== locale).map((item) => item.replace("-", "_")),
      type: "website",
      images: [{ url: absoluteUrl(siteConfig.ogImage), width: 1200, height: 630, alt: content.title }]
    },
    twitter: { card: "summary_large_image", title: content.title, description: content.ogDescription, images: [absoluteUrl(siteConfig.ogImage)] }
  };
}
