import type { Metadata } from "next";
import { absoluteUrl, siteConfig } from "@/lib/site-config";

export const locales = ["es-BO", "en", "pt-BR", "qu-BO"] as const;
export type Locale = (typeof locales)[number];

export const localeRoutes: Record<Locale, string> = {
  "es-BO": "/",
  en: "/en",
  "pt-BR": "/pt",
  "qu-BO": "/qu"
};

export const localeLabels: Record<Locale, { short: string; name: string }> = {
  "es-BO": { short: "ES", name: "Español" },
  en: { short: "EN", name: "English" },
  "pt-BR": { short: "PT", name: "Português" },
  "qu-BO": { short: "QU", name: "Quechua" }
};

const es = {
  meta: {
    title: "AgroEscudo | Monitoreo inteligente para silos y almacenamiento de granos",
    description: "Tecnología boliviana de monitoreo postcosecha con sensores IoT, alertas, historial y reportes para silos, galpones, centros de acopio y granos almacenados.",
    ogDescription: "Sensores IoT, alertas, historial operativo y reportes para monitoreo postcosecha en Cochabamba y Santa Cruz, Bolivia."
  },
  nav: { product: "Solución", how: "Cómo funciona", platform: "Plataforma", agrotech: "AgroTECH", progress: "Avances", ecosystem: "Ecosistema", press: "Prensa", pilot: "Piloto", login: "Ingresar", cta: "Solicitar piloto", open: "Abrir menú", close: "Cerrar menú", home: "AgroEscudo inicio" },
  hero: {
    alt: "Visual conceptual fotorrealista de un silo y un nodo de monitoreo AgroEscudo",
    eyebrow: "AgTech boliviana para protección postcosecha",
    brand: "AgroEscudo.",
    title: "El escudo digital del grano boliviano.",
    promise: "El grano no avisa. AgroEscudo sí.",
    copy: "Monitoreamos condiciones críticas en silos y centros de acopio para actuar antes de que el riesgo se convierta en pérdida.",
    note: "Instalación conceptual. La configuración final se define según cada sitio.",
    primary: "Solicitar un piloto", secondary: "Ver cómo funciona", tertiary: "Ingresar", microcopy: "Sensores IoT · Alertas · Historial · Bitácora · Reportes", location: "Preparación de pilotos en Cochabamba y Santa Cruz.",
    readings: [["Temperatura", "Lectura continua"], ["Humedad", "Umbral definido"], ["Estado", "Nodo conectado"]]
  },
  capabilities: { aria: "Capacidades desarrolladas", items: [["IoT", "Nodo funcional"], ["LoRa", "Comunicación probada"], ["Web + Android", "Producto MVP"], ["Bolivia", "Cochabamba y Santa Cruz"]] },
  problem: {
    eyebrow: "El riesgo invisible", title: "El problema no comienza cuando el grano se pierde.",
    copy: "Comienza cuando nadie puede ver a tiempo qué está pasando dentro del almacenamiento.",
    support: "Temperatura, humedad y tendencia convierten una inspección aislada en una decisión con evidencia.",
    visual: "Condiciones invisibles. Decisiones tardías. Sin historial.", signals: [["Temperatura", "Cambio térmico"], ["Humedad", "Condición ambiental"], ["Tendencia", "Evolución del riesgo"]]
  },
  solution: {
    eyebrow: "Sistema AgroEscudo", title: "Un sistema completo. No un sensor aislado.",
    copy: "El nodo registra variables críticas. La comunicación LoRa protege la continuidad del flujo y la plataforma convierte lecturas en información operativa que el equipo puede consultar y documentar.",
    items: [["Nodo", "Registra variables"], ["LoRa", "Transporta lecturas"], ["Gateway", "Concentra datos"], ["Plataforma", "Ordena el historial"], ["Alerta", "Activa respuesta"]],
    status: "Arquitectura MVP desarrollada para validación de campo.", flow: "Sensor → evidencia → decisión"
  },
  how: {
    eyebrow: "Cómo funciona", title: "Del grano a la alerta, sin puntos ciegos.",
    steps: [["Instalamos", "El nodo se adapta al sitio y registra variables acordadas con el operador."], ["Monitoreamos", "Las lecturas se guardan y transmiten periódicamente, incluso con conectividad intermitente."], ["Alertamos", "El sistema identifica condiciones fuera de los rangos configurados para el piloto."], ["Documentamos", "El historial, las alertas y las acciones quedan disponibles para seguimiento y reportes."]]
  },
  architecture: { aria: "Diagrama de la arquitectura AgroEscudo", alt: "Diagrama conceptual del sistema AgroEscudo: grano, sondas, LoRa, gateway, API, dashboard y alertas", caption: "Arquitectura conceptual del MVP. La cantidad y ubicación de sondas, así como la conectividad, dependen de cada instalación.", labels: { silo: "Silo + grano", probes: "Sondas internas", node: "SiloSensor", lora: "LoRa local", gateway: "Gateway", gatewayDetail: "Guarda y sincroniza", cloud: "Internet + API", cloudDetail: "Datos disponibles", platform: "Dashboard + app", platformDetail: "Alertas · historial · reportes", alert: "Alerta", grain: "Temperatura del grano", ambient: "Ambiente", connection: "Batería y conexión" }, items: [["SiloSensor", "Mide variables acordadas"], ["LoRa", "Comunicación local"], ["Gateway", "Almacena y sincroniza"], ["Internet + API", "Organiza las lecturas"], ["Plataforma", "Alertas, historial y reportes"]] },
  platform: {
    eyebrow: "Plataforma desarrollada", title: "Todos los datos. Una sola operación.", copy: "Condiciones actuales, alertas, historial y evidencia operativa para que el dato no se quede dentro del sensor.",
    items: ["Estado general", "Alertas", "Historial", "Reportes"], window: "Plataforma AgroEscudo · vista demostrativa",
    alt: "Vista real de la plataforma AgroEscudo con estado operativo, alertas e indicadores", note: "Captura del MVP existente con información demostrativa.", login: "Ingresar a la plataforma", demo: "Solicitar una demostración"
  },
  credibility: { press: "Presentado en La Razón", ecosystem: "Acompañamiento institucional", technology: "MVP IoT desarrollado", local: "Tecnología boliviana" },
  film: {
    eyebrow: "AgroEscudo en movimiento", title: "Del silo al dato. Del dato a la decisión.",
    copy: "Una visión del sistema que conecta sensores, comunicación y plataforma para convertir condiciones del almacenamiento en información operativa.",
    note: "Representación audiovisual conceptual del sistema y del MVP. No corresponde a una instalación comercial ni a un piloto ejecutado.",
    controls: "Controles del video", play: "Reproducir video", pause: "Pausar video", soundOn: "Activar sonido", soundOff: "Silenciar video",
    railLabel: "Flujo del sistema AgroEscudo", rail: ["SiloSensor", "LoRa local", "Gateway", "API", "Alerta", "Decisión"]
  },
  product: { eyebrow: "Solución", title: "Medir. Detectar. Actuar.", copy: "Un sistema completo para convertir señales del almacenamiento en acciones operativas.", items: [["Monitoreo", "Lecturas continuas de las variables definidas para el sitio."], ["Alertas", "Avisos configurables cuando una condición sale de rango."], ["Historial y bitácora", "Eventos y acciones reunidos en una fuente compartida."], ["Reportes", "Evidencia clara para seguimiento técnico y operativo."]] },
  why: { eyebrow: "Por qué AgroEscudo", title: "Diseñado para operar en el contexto real de Bolivia.", items: [["Tecnología local", "Desarrollo cercano a la realidad de almacenamiento y postcosecha del país."], ["Conectividad intermitente", "La arquitectura contempla guardar y sincronizar lecturas cuando vuelve la conexión."], ["Enfoque B2B", "Pensado para responsables de inventario, calidad y continuidad operativa."]] },
  agrotech: {
    eyebrow: "AgroTECH Bolivia 2026", title: "AgroEscudo llevó la protección postcosecha al escenario de AgroTECH.",
    copy: "Brayan Javier Mejía Saavedra y el equipo presentaron el sistema ante actores del sector agropecuario, explicando el riesgo, las variables críticas y el flujo del sensor a la decisión.",
    date: "28 y 29 de julio de 2026", location: "Santa Cruz · Bolivia", link: "Ver reconocimiento público",
    videoTitle: "Presentación de AgroEscudo en escenario", videoCaption: "Registro real del pitch sobre monitoreo, alertas tempranas y protección del grano almacenado.",
    teamLabel: "Equipo AgroEscudo", teamAlt: "Equipo AgroEscudo en su stand de AgroTECH Bolivia 2026", teamCaption: "Equipo y prototipos presentados en el stand de AgroEscudo.",
    galleryLabel: "Registro del evento", galleryCopy: "Escenario, arquitectura, stand y articulación con el sector.", open: "Ampliar imagen", close: "Cerrar galería", previous: "Imagen anterior", next: "Imagen siguiente",
    items: [
      ["Auditorio de AgroTECH Bolivia 2026 durante una presentación técnica", "AgroTECH reunió a actores del sector agropecuario y la innovación."],
      ["Equipo AgroEscudo explicando el riesgo postcosecha en el escenario", "El problema postcosecha explicado ante el público del evento."],
      ["Presentación del flujo SiloSensor, gateway, plataforma, alerta y acción", "La arquitectura AgroEscudo, del sensor a la decisión."],
      ["Demostración del sistema AgroEscudo en el área de stands", "Conversaciones técnicas y demostración del sistema en el stand."],
      ["Participantes y organizaciones reunidas en AgroTECH Bolivia 2026", "Encuentro con el ecosistema agropecuario y de innovación."]
    ]
  },
  progress: {
    eyebrow: "Avances verificables", title: "Del prototipo a una operación piloto.", copy: "Mostramos la etapa de cada componente tal como es hoy. La siguiente prueba relevante es conectar la tecnología desarrollada con condiciones reales de almacenamiento.",
    items: [["Nodo y comunicación LoRa", "Probado en laboratorio"], ["API y almacenamiento de lecturas", "Desarrollado"], ["Dashboard web", "Desplegado"], ["Aplicación Android", "Versión MVP"], ["Recuperación ante desconexión", "En validación"], ["Instalación en operación real", "Próximo piloto"]]
  },
  founder: {
    role: "Fundador y CEO", location: "Cochabamba · Bolivia", alt: "Brayan Javier Mejía Saavedra, fundador y CEO de AgroEscudo",
    lead: "Lidera la construcción y validación de AgroEscudo, conectando tecnología IoT con necesidades reales de almacenamiento y postcosecha.",
    copy: "Su trabajo integra visión de producto, desarrollo tecnológico y preparación de pilotos para convertir datos de silos y galpones en decisiones operativas más oportunas.",
    principle: "Principio de trabajo", quote: "Tecnología útil, evidencia operativa y validación en campo.", contact: "Conversar con Brayan", interview: "Leer entrevista en La Razón"
  },
  ecosystem: {
    eyebrowTop: "Ecosistema institucional", headline: "Respaldados por un ecosistema que impulsa la innovación boliviana.", eyebrow: "Organizaciones que nos respaldan", title: "Apoyo real para avanzar con más rigor.",
    copy: "AgroEscudo fortalece su desarrollo tecnológico, comercial y académico con el respaldo de organizaciones bolivianas vinculadas a la innovación, la incubación empresarial y la formación técnica.",
    categories: ["Preaceleración", "Incubación tecnológica", "Respaldo académico", "Acompañamiento técnico"],
    descriptions: ["Fortalecimiento empresarial y preparación para conectar la solución con el mercado.", "Articulación dentro del ecosistema de innovación y preaceleración empresarial.", "Respaldo institucional vinculado al proceso de fortalecimiento empresarial de Innova Up.", "Acompañamiento para estructuración, incubación y desarrollo de la empresa tecnológica.", "Acompañamiento académico al desarrollo tecnológico del equipo fundador.", "Entorno académico vinculado a EMBATE y a la articulación técnica del proyecto.", "Articulación técnica para fortalecer la validación aplicada en el sector agrícola."],
    disclaimer: "El respaldo corresponde a procesos de acompañamiento, incubación, preaceleración y articulación institucional; no implica inversión, certificación ni relación comercial."
  },
  clients: {
    eyebrow: "Para quién es", title: "Para operaciones donde conocer tarde cuesta más.", riskLabel: "Riesgo operativo", decisionLabel: "Decisión que mejora",
    items: [["Protección de inventario", "Silos · galpones · centros de acopio", "Inventario concentrado expuesto a cambios que una ronda ocasional puede no revelar.", "Priorizar inspección, ventilación o seguimiento según evidencia."], ["Continuidad operativa", "Molinos · alimentos balanceados · agroindustria", "Una condición fuera de rango puede afectar recepción, almacenamiento y programación de planta.", "Coordinar respuesta antes de que el evento comprometa el proceso siguiente."], ["Supervisión y trazabilidad", "Cooperativas · calidad · administradores multisitio", "Sin historial común, comparar sitios y justificar acciones consume tiempo operativo.", "Revisar eventos, responsables y acciones desde una fuente compartida."]]
  },
  press: {
    eyebrow: "Prensa, reconocimientos y cobertura", title: "AgroEscudo en el ecosistema de innovación.", copy: "Cobertura, reconocimiento y participación pública de una tecnología boliviana enfocada en reducir el riesgo postcosecha con monitoreo de silos, galpones y centros de acopio.",
    cover: "Portada del suplemento", article: "Entrevista publicada", evidence: "Evidencia editorial", sourceNote: "Ver la publicación en su fuente original.", open: "Abrir fuente", more: "Más cobertura indexable de AgroEscudo", moreCopy: "Prensa, reconocimientos y participación pública, separados de clientes, inversión o certificaciones.", moreLink: "Ver página de prensa", readAria: "Leer cobertura de AgroEscudo en"
  },
  pilot: {
    eyebrow: "Próximo piloto", title: "Tu instalación puede ser el próximo piloto AgroEscudo.", copy: "Buscamos operaciones de almacenamiento, acopio y transformación en Cochabamba y Santa Cruz para validar el sistema en condiciones reales y medir disponibilidad, eventos detectados y tiempos de respuesta.",
    location: "Cochabamba · Santa Cruz", primary: "Solicitar evaluación del sitio", secondary: "Hablar por WhatsApp", note: "La evaluación confirma si el caso tiene sentido operativo. No implica piloto gratuito ni compromiso de compra.", route: "Ruta de validación", stages: ["Evaluación inicial del sitio", "Definición de variables y umbrales", "Instalación y monitoreo", "Informe de resultados"], observe: "Qué se observa", metrics: ["Disponibilidad del sistema", "Eventos detectados", "Tiempo de respuesta", "Acciones registradas"]
  },
  faq: {
    eyebrow: "Preguntas frecuentes", title: "Lo básico para evaluar AgroEscudo sin vueltas.", copy: "Respuestas directas para operadores que están considerando monitoreo de silos, granos almacenados e IoT agrícola en Bolivia.",
    items: [["¿Qué monitorea AgroEscudo?", "AgroEscudo monitorea temperatura y humedad en silos, galpones y centros de acopio para detectar condiciones de riesgo postcosecha y apoyar decisiones operativas."], ["¿AgroEscudo funciona sin internet permanente?", "El piloto se diseña considerando conectividad variable. La arquitectura contempla operación en campo y seguimiento de lecturas para no depender de una conexión ideal."], ["¿Dónde puede instalarse?", "Puede evaluarse en silos, galpones, centros de acopio, molinos, cooperativas, plantas de alimentos balanceados y agroindustrias con inventario agrícola almacenado."], ["¿Está disponible en Cochabamba y Santa Cruz?", "Sí. La primera etapa de validación comercial prioriza instalaciones piloto en Cochabamba y Santa Cruz, Bolivia."], ["¿Cómo se solicita un piloto?", "El primer paso es escribir por WhatsApp para coordinar una revisión del sitio. Con esa información se define si el caso operativo merece un piloto de 60 a 90 días."], ["¿AgroEscudo reemplaza el manejo técnico del silo?", "No. AgroEscudo no reemplaza la experiencia del operador. Aporta datos, alertas, historial y evidencia para apoyar decisiones de manejo."], ["¿Los sensores se venden o se entregan como servicio?", "En esta etapa se prioriza el piloto operativo. El modelo final se define según el sitio, los nodos requeridos, el acompañamiento y la necesidad de reportes."], ["¿Qué tipo de operaciones pueden evaluar AgroEscudo?", "AgroEscudo está pensado para operaciones con granos almacenados, inventario agrícola, silos, galpones, plantas, centros de acopio y agroindustrias que necesitan visibilidad y trazabilidad."]]
  },
  cta: { eyebrow: "Contacto directo", title: "¿Tienes grano almacenado y necesitas mayor visibilidad?", copy: "Conversemos sobre tu sitio, las variables críticas y el alcance de un posible piloto.", location: "Cochabamba y Santa Cruz, Bolivia", email: "Correo" },
  footer: { description: "AgroEscudo desarrolla tecnología de monitoreo para reducir riesgos operativos y postcosecha en silos, galpones y centros de acopio.", navigation: "Navegación", contact: "Contacto", location: "Operación inicial en Cochabamba y Santa Cruz, Bolivia.", rights: "Todos los derechos reservados.", tagline: "Monitoreo inteligente para proteger granos almacenados.", fullPress: "Cobertura completa" },
  whatsapp: "Hablar con AgroEscudo"
};

const en: typeof es = {
  meta: { title: "AgroEscudo | Smart monitoring for silos and stored grain", description: "Bolivian post-harvest monitoring technology combining IoT sensors, alerts, operational history, and reports for silos and grain storage facilities.", ogDescription: "IoT sensors, alerts, operational history, and reports for post-harvest monitoring in Cochabamba and Santa Cruz, Bolivia." },
  nav: { product: "Solution", how: "How it works", platform: "Platform", agrotech: "AgroTECH", progress: "Progress", ecosystem: "Ecosystem", press: "Press", pilot: "Pilot", login: "Sign in", cta: "Request a pilot", open: "Open menu", close: "Close menu", home: "AgroEscudo home" },
  hero: { alt: "Photorealistic conceptual view of a grain silo and AgroEscudo monitoring node", eyebrow: "Bolivian AgTech for post-harvest protection", brand: "AgroEscudo.", title: "The digital shield for Bolivian grain.", promise: "Grain does not warn you. AgroEscudo does.", copy: "We monitor critical conditions in silos and collection facilities so teams can act before risk becomes loss.", note: "Conceptual installation. Final configuration depends on each site.", primary: "Request a pilot", secondary: "See how it works", tertiary: "Sign in", microcopy: "IoT sensors · Alerts · History · Logbook · Reports", location: "Pilot preparation in Cochabamba and Santa Cruz.", readings: [["Temperature", "Continuous reading"], ["Humidity", "Defined threshold"], ["Status", "Node connected"]] },
  capabilities: { aria: "Developed capabilities", items: [["IoT", "Functional node"], ["LoRa", "Tested communication"], ["Web + Android", "MVP product"], ["Bolivia", "Cochabamba and Santa Cruz"]] },
  problem: { eyebrow: "The invisible risk", title: "The problem does not begin when grain is lost.", copy: "It begins when no one can see what is happening inside storage in time.", support: "Temperature, humidity, and trend turn an isolated inspection into an evidence-based decision.", visual: "Invisible conditions. Late decisions. No history.", signals: [["Temperature", "Thermal change"], ["Humidity", "Environmental condition"], ["Trend", "Risk evolution"]] },
  solution: { eyebrow: "AgroEscudo system", title: "A complete system. Not an isolated sensor.", copy: "The node records critical variables. LoRa communication supports data continuity, while the platform turns readings into operational information the team can review and document.", items: [["Node", "Records variables"], ["LoRa", "Transmits readings"], ["Gateway", "Concentrates data"], ["Platform", "Organizes history"], ["Alert", "Triggers response"]], status: "MVP architecture developed for field validation.", flow: "Sensor → evidence → decision" },
  how: { eyebrow: "How it works", title: "From grain to alert, without blind spots.", steps: [["We install", "The node is adapted to the site and records variables agreed with the operator."], ["We monitor", "Readings are stored and transmitted periodically, even with intermittent connectivity."], ["We alert", "The system identifies conditions outside the thresholds configured for the pilot."], ["We document", "History, alerts, and actions remain available for follow-up and reports."]] },
  architecture: { aria: "AgroEscudo architecture diagram", alt: "Conceptual AgroEscudo system diagram: grain, probes, LoRa, gateway, API, dashboard, and alerts", caption: "Conceptual MVP architecture. Probe count and placement, as well as connectivity, depend on each facility.", labels: { silo: "Silo + grain", probes: "Internal probes", node: "SiloSensor", lora: "Local LoRa", gateway: "Gateway", gatewayDetail: "Stores and syncs", cloud: "Internet + API", cloudDetail: "Data available", platform: "Dashboard + app", platformDetail: "Alerts · history · reports", alert: "Alert", grain: "Grain temperature", ambient: "Environment", connection: "Battery and connection" }, items: [["SiloSensor", "Measures agreed variables"], ["LoRa", "Local communication"], ["Gateway", "Stores and synchronizes"], ["Internet + API", "Organizes readings"], ["Platform", "Alerts, history, and reports"]] },
  platform: { eyebrow: "Platform developed", title: "All the data. One operation.", copy: "Current conditions, alerts, history, and operational evidence so data does not remain trapped inside the sensor.", items: ["Overall status", "Alerts", "History", "Reports"], window: "AgroEscudo platform · demonstration view", alt: "AgroEscudo platform showing operational status, alerts, and indicators", note: "Screenshot of the existing MVP with demonstration data.", login: "Sign in to the platform", demo: "Request a demonstration" },
  credibility: { press: "Featured in La Razón", ecosystem: "Institutional support", technology: "IoT MVP developed", local: "Bolivian technology" },
  film: { eyebrow: "AgroEscudo in motion", title: "From silo to data. From data to decision.", copy: "A view of the system connecting sensors, communications, and platform to turn storage conditions into operational information.", note: "Conceptual audiovisual representation of the system and MVP. It does not depict a commercial installation or a completed pilot.", controls: "Video controls", play: "Play video", pause: "Pause video", soundOn: "Turn sound on", soundOff: "Mute video", railLabel: "AgroEscudo system flow", rail: ["SiloSensor", "Local LoRa", "Gateway", "API", "Alert", "Decision"] },
  product: { eyebrow: "Solution", title: "Measure. Detect. Act.", copy: "A complete system that turns storage signals into operational action.", items: [["Monitoring", "Continuous readings of the variables defined for the site."], ["Alerts", "Configurable notices when a condition moves out of range."], ["History and logbook", "Events and actions brought together in one shared source."], ["Reports", "Clear evidence for technical and operational follow-up."]] },
  why: { eyebrow: "Why AgroEscudo", title: "Designed for Bolivia's operating reality.", items: [["Local technology", "Development close to the country's storage and post-harvest context."], ["Intermittent connectivity", "The architecture can store and synchronize readings when connectivity returns."], ["B2B focus", "Built for inventory, quality, and operational continuity teams."]] },
  agrotech: {
    eyebrow: "AgroTECH Bolivia 2026", title: "AgroEscudo brought post-harvest protection to the AgroTECH stage.", copy: "Brayan Javier Mejía Saavedra and the team presented the system to agricultural industry stakeholders, explaining the risk, critical variables, and the flow from sensor to decision.", date: "July 28–29, 2026", location: "Santa Cruz · Bolivia", link: "View public recognition", videoTitle: "AgroEscudo on the main stage", videoCaption: "Real footage of the pitch on monitoring, early alerts, and stored grain protection.", teamLabel: "AgroEscudo team", teamAlt: "AgroEscudo team at its AgroTECH Bolivia 2026 stand", teamCaption: "Team and prototypes presented at the AgroEscudo stand.", galleryLabel: "Event record", galleryCopy: "Stage, architecture, stand, and engagement with the industry.", open: "Enlarge image", close: "Close gallery", previous: "Previous image", next: "Next image", items: [["AgroTECH Bolivia 2026 auditorium during a technical presentation", "AgroTECH brought together agricultural and innovation stakeholders."], ["AgroEscudo team explaining post-harvest risk on stage", "The post-harvest challenge explained to the event audience."], ["Presentation of the SiloSensor, gateway, platform, alert, and action flow", "AgroEscudo architecture, from sensor to decision."], ["AgroEscudo system demonstration in the exhibition area", "Technical conversations and a system demonstration at the stand."], ["Participants and organizations gathered at AgroTECH Bolivia 2026", "Engagement with the agricultural and innovation ecosystem."]]
  },
  progress: { eyebrow: "Verifiable progress", title: "From prototype to a pilot operation.", copy: "We show each component's current stage as it is today. The next relevant test is connecting the developed technology with real storage conditions.", items: [["Node and LoRa communication", "Laboratory tested"], ["API and reading storage", "Developed"], ["Web dashboard", "Deployed"], ["Android application", "MVP version"], ["Disconnection recovery", "Under validation"], ["Installation in a real operation", "Next pilot"]] },
  founder: { role: "Founder and CEO", location: "Cochabamba · Bolivia", alt: "Brayan Javier Mejía Saavedra, founder and CEO of AgroEscudo", lead: "He leads the development and validation of AgroEscudo, connecting IoT technology with real storage and post-harvest needs.", copy: "His work combines product vision, technology development, and pilot preparation to turn silo and warehouse data into more timely operational decisions.", principle: "Working principle", quote: "Useful technology, operational evidence, and field validation.", contact: "Talk with Brayan", interview: "Read the La Razón interview" },
  ecosystem: { eyebrowTop: "Institutional ecosystem", headline: "Supported by an ecosystem advancing Bolivian innovation.", eyebrow: "Organizations supporting us", title: "Real support to move forward with greater rigor.", copy: "AgroEscudo strengthens its technological, commercial, and academic development with support from Bolivian organizations connected to innovation, business incubation, and technical education.", categories: ["Pre-acceleration", "Technology incubation", "Academic support", "Technical support"], descriptions: ["Business strengthening and preparation to connect the solution with the market.", "Connection within the innovation ecosystem and business pre-acceleration.", "Institutional support linked to the Innova Up business strengthening process.", "Support for structuring, incubating, and developing the technology venture.", "Academic support for the founding team's technology development.", "Academic environment connected to EMBATE and the project's technical coordination.", "Technical coordination to strengthen applied validation in the agricultural sector."], disclaimer: "Support refers to mentoring, incubation, pre-acceleration, and institutional coordination processes; it does not imply investment, certification, or a commercial relationship." },
  clients: { eyebrow: "Who it is for", title: "For operations where learning late costs more.", riskLabel: "Operational risk", decisionLabel: "Decision improved", items: [["Inventory protection", "Silos · warehouses · grain collection facilities", "Concentrated inventory exposed to changes that an occasional inspection may not reveal.", "Prioritize inspection, ventilation, or follow-up based on evidence."], ["Operational continuity", "Mills · feed plants · agribusiness", "An out-of-range condition may affect reception, storage, and plant scheduling.", "Coordinate a response before the event compromises the next process."], ["Supervision and traceability", "Cooperatives · quality teams · multi-site managers", "Without shared history, comparing sites and justifying actions consumes operational time.", "Review events, responsible teams, and actions from one shared source."]] },
  press: { eyebrow: "Press, recognition, and coverage", title: "AgroEscudo in the innovation ecosystem.", copy: "Coverage, recognition, and public participation of a Bolivian technology focused on reducing post-harvest risk through silo, warehouse, and grain collection monitoring.", cover: "Supplement cover", article: "Published interview", evidence: "Editorial evidence", sourceNote: "View the publication at its original source.", open: "Open source", more: "More indexable coverage of AgroEscudo", moreCopy: "Press, recognition, and public participation, clearly separated from customers, investment, or certifications.", moreLink: "View press page", readAria: "Read AgroEscudo coverage in" },
  pilot: { eyebrow: "Next pilot", title: "Your facility could be the next AgroEscudo pilot.", copy: "We are looking for storage, collection, and processing operations in Cochabamba and Santa Cruz to validate the system under real conditions and measure availability, detected events, and response times.", location: "Cochabamba · Santa Cruz", primary: "Request a site assessment", secondary: "Talk on WhatsApp", note: "The assessment confirms whether the use case makes operational sense. It does not imply a free pilot or purchase commitment.", route: "Validation path", stages: ["Initial site assessment", "Definition of variables and thresholds", "Installation and monitoring", "Results report"], observe: "What is observed", metrics: ["System availability", "Detected events", "Response time", "Recorded actions"] },
  faq: { eyebrow: "Frequently asked questions", title: "The essentials for evaluating AgroEscudo.", copy: "Direct answers for operators considering silo monitoring, stored grain, and agricultural IoT in Bolivia.", items: [["What does AgroEscudo monitor?", "AgroEscudo monitors temperature and humidity in silos, warehouses, and collection facilities to identify post-harvest risk conditions and support operational decisions."], ["Does AgroEscudo work without permanent internet?", "The pilot is designed for variable connectivity. The architecture considers field operation and reading continuity without depending on an ideal connection."], ["Where can it be installed?", "It can be assessed for silos, warehouses, collection facilities, mills, cooperatives, feed plants, and agribusinesses with stored agricultural inventory."], ["Is it available in Cochabamba and Santa Cruz?", "Yes. The first commercial validation stage prioritizes pilot facilities in Cochabamba and Santa Cruz, Bolivia."], ["How can I request a pilot?", "The first step is to contact us on WhatsApp to coordinate a site review. This information helps determine whether the operational case merits a 60 to 90 day pilot."], ["Does AgroEscudo replace technical silo management?", "No. AgroEscudo does not replace operator experience. It provides data, alerts, history, and evidence to support management decisions."], ["Are sensors sold or provided as a service?", "At this stage, the operational pilot is the priority. The final model depends on the site, required nodes, support, and reporting needs."], ["What kinds of operations can evaluate AgroEscudo?", "AgroEscudo is designed for operations with stored grain, agricultural inventory, silos, warehouses, plants, collection facilities, and agribusinesses that need visibility and traceability."]] },
  cta: { eyebrow: "Direct contact", title: "Do you store grain and need greater visibility?", copy: "Let us discuss your facility, its critical variables, and the scope of a possible pilot.", location: "Cochabamba and Santa Cruz, Bolivia", email: "Email" },
  footer: { description: "AgroEscudo develops monitoring technology to reduce operational and post-harvest risks in silos, warehouses, and grain collection facilities.", navigation: "Navigation", contact: "Contact", location: "Initial operations in Cochabamba and Santa Cruz, Bolivia.", rights: "All rights reserved.", tagline: "Smart monitoring to protect stored grain.", fullPress: "Full coverage" },
  whatsapp: "Talk with AgroEscudo"
};

const pt: typeof es = {
  meta: { title: "AgroEscudo | Monitoramento inteligente para silos e grãos armazenados", description: "Tecnologia boliviana de monitoramento pós-colheita com sensores IoT, alertas, histórico operacional e relatórios para silos, armazéns e centros de coleta de grãos.", ogDescription: "Sensores IoT, alertas, histórico operacional e relatórios para monitoramento pós-colheita em Cochabamba e Santa Cruz, Bolívia." },
  nav: { product: "Solução", how: "Como funciona", platform: "Plataforma", agrotech: "AgroTECH", progress: "Avanços", ecosystem: "Ecossistema", press: "Imprensa", pilot: "Piloto", login: "Entrar", cta: "Solicitar piloto", open: "Abrir menu", close: "Fechar menu", home: "Início AgroEscudo" },
  hero: { alt: "Visual conceitual fotorrealista de um silo e um nó de monitoramento AgroEscudo", eyebrow: "AgTech boliviana para proteção pós-colheita", brand: "AgroEscudo.", title: "O escudo digital do grão boliviano.", promise: "O grão não avisa. A AgroEscudo avisa.", copy: "Monitoramos condições críticas em silos e centros de coleta para agir antes que o risco se transforme em perda.", note: "Instalação conceitual. A configuração final é definida de acordo com cada local.", primary: "Solicitar um piloto", secondary: "Ver como funciona", tertiary: "Entrar", microcopy: "Sensores IoT · Alertas · Histórico · Registro · Relatórios", location: "Preparação de pilotos em Cochabamba e Santa Cruz.", readings: [["Temperatura", "Leitura contínua"], ["Umidade", "Limite definido"], ["Status", "Nó conectado"]] },
  capabilities: { aria: "Capacidades desenvolvidas", items: [["IoT", "Nó funcional"], ["LoRa", "Comunicação testada"], ["Web + Android", "Produto MVP"], ["Bolívia", "Cochabamba e Santa Cruz"]] },
  problem: { eyebrow: "O risco invisível", title: "O problema não começa quando o grão é perdido.", copy: "Começa quando ninguém consegue ver a tempo o que está acontecendo dentro do armazenamento.", support: "Temperatura, umidade e tendência transformam uma inspeção isolada em uma decisão baseada em evidências.", visual: "Condições invisíveis. Decisões tardias. Sem histórico.", signals: [["Temperatura", "Variação térmica"], ["Umidade", "Condição ambiental"], ["Tendência", "Evolução do risco"]] },
  solution: { eyebrow: "Sistema AgroEscudo", title: "Um sistema completo. Não um sensor isolado.", copy: "O nó registra variáveis críticas. A comunicação LoRa apoia a continuidade do fluxo e a plataforma transforma leituras em informação operacional que a equipe pode consultar e documentar.", items: [["Nó", "Registra variáveis"], ["LoRa", "Transmite leituras"], ["Gateway", "Concentra dados"], ["Plataforma", "Organiza o histórico"], ["Alerta", "Ativa a resposta"]], status: "Arquitetura MVP desenvolvida para validação em campo.", flow: "Sensor → evidência → decisão" },
  how: { eyebrow: "Como funciona", title: "Do grão ao alerta, sem pontos cegos.", steps: [["Instalamos", "O nó é adaptado ao local e registra as variáveis acordadas com o operador."], ["Monitoramos", "As leituras são armazenadas e transmitidas periodicamente, mesmo com conectividade intermitente."], ["Alertamos", "O sistema identifica condições fora dos limites configurados para o piloto."], ["Documentamos", "O histórico, os alertas e as ações ficam disponíveis para acompanhamento e relatórios."]] },
  architecture: { aria: "Diagrama da arquitetura AgroEscudo", alt: "Diagrama conceitual do sistema AgroEscudo: grão, sondas, LoRa, gateway, API, dashboard e alertas", caption: "Arquitetura conceitual do MVP. A quantidade e a posição das sondas, assim como a conectividade, dependem de cada instalação.", labels: { silo: "Silo + grão", probes: "Sondas internas", node: "SiloSensor", lora: "LoRa local", gateway: "Gateway", gatewayDetail: "Armazena e sincroniza", cloud: "Internet + API", cloudDetail: "Dados disponíveis", platform: "Dashboard + app", platformDetail: "Alertas · histórico · relatórios", alert: "Alerta", grain: "Temperatura do grão", ambient: "Ambiente", connection: "Bateria e conexão" }, items: [["SiloSensor", "Mede as variáveis acordadas"], ["LoRa", "Comunicação local"], ["Gateway", "Armazena e sincroniza"], ["Internet + API", "Organiza as leituras"], ["Plataforma", "Alertas, histórico e relatórios"]] },
  platform: { eyebrow: "Plataforma desenvolvida", title: "Todos os dados. Uma única operação.", copy: "Condições atuais, alertas, histórico e evidências operacionais para que os dados não fiquem presos no sensor.", items: ["Visão geral", "Alertas", "Histórico", "Relatórios"], window: "Plataforma AgroEscudo · visualização demonstrativa", alt: "Plataforma AgroEscudo com status operacional, alertas e indicadores", note: "Captura do MVP existente com dados demonstrativos.", login: "Entrar na plataforma", demo: "Solicitar uma demonstração" },
  credibility: { press: "Destaque em La Razón", ecosystem: "Apoio institucional", technology: "MVP IoT desenvolvido", local: "Tecnologia boliviana" },
  film: { eyebrow: "AgroEscudo em movimento", title: "Do silo ao dado. Do dado à decisão.", copy: "Uma visão do sistema que conecta sensores, comunicação e plataforma para transformar condições de armazenamento em informação operacional.", note: "Representação audiovisual conceitual do sistema e do MVP. Não corresponde a uma instalação comercial nem a um piloto executado.", controls: "Controles do vídeo", play: "Reproduzir vídeo", pause: "Pausar vídeo", soundOn: "Ativar som", soundOff: "Silenciar vídeo", railLabel: "Fluxo do sistema AgroEscudo", rail: ["SiloSensor", "LoRa local", "Gateway", "API", "Alerta", "Decisão"] },
  product: { eyebrow: "Solução", title: "Medir. Detectar. Agir.", copy: "Um sistema completo para transformar sinais do armazenamento em ações operacionais.", items: [["Monitoramento", "Leituras contínuas das variáveis definidas para o local."], ["Alertas", "Avisos configuráveis quando uma condição sai do intervalo."], ["Histórico e registro", "Eventos e ações reunidos em uma fonte compartilhada."], ["Relatórios", "Evidências claras para acompanhamento técnico e operacional."]] },
  why: { eyebrow: "Por que AgroEscudo", title: "Projetado para operar na realidade da Bolívia.", items: [["Tecnologia local", "Desenvolvimento próximo à realidade de armazenamento e pós-colheita do país."], ["Conectividade intermitente", "A arquitetura pode armazenar e sincronizar leituras quando a conexão retorna."], ["Foco B2B", "Pensado para responsáveis por estoque, qualidade e continuidade operacional."]] },
  agrotech: {
    eyebrow: "AgroTECH Bolívia 2026", title: "A AgroEscudo levou a proteção pós-colheita ao palco da AgroTECH.", copy: "Brayan Javier Mejía Saavedra e a equipe apresentaram o sistema a atores do setor agropecuário, explicando o risco, as variáveis críticas e o fluxo do sensor à decisão.", date: "28 e 29 de julho de 2026", location: "Santa Cruz · Bolívia", link: "Ver reconhecimento público", videoTitle: "AgroEscudo no palco principal", videoCaption: "Registro real do pitch sobre monitoramento, alertas antecipados e proteção de grãos armazenados.", teamLabel: "Equipe AgroEscudo", teamAlt: "Equipe AgroEscudo em seu estande na AgroTECH Bolívia 2026", teamCaption: "Equipe e protótipos apresentados no estande da AgroEscudo.", galleryLabel: "Registro do evento", galleryCopy: "Palco, arquitetura, estande e contato com o setor.", open: "Ampliar imagem", close: "Fechar galeria", previous: "Imagem anterior", next: "Próxima imagem", items: [["Auditório da AgroTECH Bolívia 2026 durante uma apresentação técnica", "A AgroTECH reuniu atores do setor agropecuário e do ecossistema de inovação."], ["Equipe AgroEscudo explicando o risco pós-colheita no palco", "O desafio pós-colheita apresentado ao público do evento."], ["Apresentação do fluxo SiloSensor, gateway, plataforma, alerta e ação", "A arquitetura da AgroEscudo, do sensor à decisão."], ["Demonstração do sistema AgroEscudo na área de exposição", "Conversas técnicas e demonstração do sistema no estande."], ["Participantes e organizações reunidos na AgroTECH Bolívia 2026", "Articulação com o ecossistema agropecuário e de inovação."]]
  },
  progress: { eyebrow: "Avanços verificáveis", title: "Do protótipo a uma operação piloto.", copy: "Apresentamos o estágio atual de cada componente com transparência. O próximo teste relevante é conectar a tecnologia desenvolvida a condições reais de armazenamento.", items: [["Nó e comunicação LoRa", "Testados em laboratório"], ["API e armazenamento de leituras", "Desenvolvidos"], ["Dashboard web", "Publicado"], ["Aplicativo Android", "Versão MVP"], ["Recuperação após desconexão", "Em validação"], ["Instalação em operação real", "Próximo piloto"]] },
  founder: { role: "Fundador e CEO", location: "Cochabamba · Bolívia", alt: "Brayan Javier Mejía Saavedra, fundador e CEO da AgroEscudo", lead: "Lidera o desenvolvimento e a validação da AgroEscudo, conectando tecnologia IoT a necessidades reais de armazenamento e pós-colheita.", copy: "Seu trabalho combina visão de produto, desenvolvimento tecnológico e preparação de pilotos para transformar dados de silos e armazéns em decisões operacionais mais oportunas.", principle: "Princípio de trabalho", quote: "Tecnologia útil, evidência operacional e validação em campo.", contact: "Falar com Brayan", interview: "Ler a entrevista em La Razón" },
  ecosystem: { eyebrowTop: "Ecossistema institucional", headline: "Apoiada por um ecossistema que impulsiona a inovação boliviana.", eyebrow: "Organizações que nos apoiam", title: "Apoio real para avançar com mais rigor.", copy: "A AgroEscudo fortalece seu desenvolvimento tecnológico, comercial e acadêmico com o apoio de organizações bolivianas ligadas à inovação, à incubação empresarial e à formação técnica.", categories: ["Pré-aceleração", "Incubação tecnológica", "Apoio acadêmico", "Acompanhamento técnico"], descriptions: ["Fortalecimento empresarial e preparação para conectar a solução ao mercado.", "Articulação no ecossistema de inovação e pré-aceleração empresarial.", "Apoio institucional vinculado ao processo de fortalecimento empresarial Innova Up.", "Acompanhamento para estruturar, incubar e desenvolver o empreendimento tecnológico.", "Apoio acadêmico ao desenvolvimento tecnológico da equipe fundadora.", "Ambiente acadêmico ligado ao EMBATE e à articulação técnica do projeto.", "Coordenação técnica para fortalecer a validação aplicada no setor agropecuário."], disclaimer: "O apoio corresponde a processos de acompanhamento, incubação, pré-aceleração e articulação institucional; não implica investimento, certificação nem relação comercial." },
  clients: { eyebrow: "Para quem é", title: "Para operações em que descobrir tarde custa mais.", riskLabel: "Risco operacional", decisionLabel: "Decisão aprimorada", items: [["Proteção de estoque", "Silos · armazéns · centros de coleta", "Estoque concentrado e exposto a mudanças que uma inspeção eventual pode não revelar.", "Priorizar inspeção, ventilação ou acompanhamento com base em evidências."], ["Continuidade operacional", "Moinhos · fábricas de ração · agroindústria", "Uma condição fora do intervalo pode afetar o recebimento, o armazenamento e a programação da planta.", "Coordenar a resposta antes que o evento comprometa o processo seguinte."], ["Supervisão e rastreabilidade", "Cooperativas · equipes de qualidade · gestores de vários locais", "Sem um histórico compartilhado, comparar locais e justificar ações consome tempo operacional.", "Revisar eventos, responsáveis e ações a partir de uma fonte compartilhada."]] },
  press: { eyebrow: "Imprensa, reconhecimento e cobertura", title: "AgroEscudo no ecossistema de inovação.", copy: "Cobertura, reconhecimento e participação pública de uma tecnologia boliviana voltada à redução do risco pós-colheita por meio do monitoramento de silos, armazéns e centros de coleta.", cover: "Capa do suplemento", article: "Entrevista publicada", evidence: "Evidência editorial", sourceNote: "Veja a publicação em sua fonte original.", open: "Abrir fonte", more: "Mais cobertura indexável sobre a AgroEscudo", moreCopy: "Imprensa, reconhecimento e participação pública, claramente separados de clientes, investimento ou certificações.", moreLink: "Ver página de imprensa", readAria: "Ler a cobertura da AgroEscudo em" },
  pilot: { eyebrow: "Próximo piloto", title: "Sua instalação pode ser o próximo piloto AgroEscudo.", copy: "Buscamos operações de armazenamento, coleta e processamento em Cochabamba e Santa Cruz para validar o sistema em condições reais e medir disponibilidade, eventos detectados e tempos de resposta.", location: "Cochabamba · Santa Cruz", primary: "Solicitar avaliação do local", secondary: "Falar pelo WhatsApp", note: "A avaliação confirma se o caso de uso faz sentido operacional. Não implica piloto gratuito nem compromisso de compra.", route: "Rota de validação", stages: ["Avaliação inicial do local", "Definição de variáveis e limites", "Instalação e monitoramento", "Relatório de resultados"], observe: "O que é observado", metrics: ["Disponibilidade do sistema", "Eventos detectados", "Tempo de resposta", "Ações registradas"] },
  faq: { eyebrow: "Perguntas frequentes", title: "O essencial para avaliar a AgroEscudo.", copy: "Respostas diretas para operadores que avaliam monitoramento de silos, grãos armazenados e IoT agrícola na Bolívia.", items: [["O que a AgroEscudo monitora?", "A AgroEscudo monitora temperatura e umidade em silos, armazéns e centros de coleta para identificar condições de risco pós-colheita e apoiar decisões operacionais."], ["A AgroEscudo funciona sem internet permanente?", "O piloto é projetado para conectividade variável. A arquitetura considera a operação em campo e a continuidade das leituras sem depender de uma conexão ideal."], ["Onde pode ser instalada?", "Pode ser avaliada em silos, armazéns, centros de coleta, moinhos, cooperativas, fábricas de ração e agroindústrias com estoque agrícola armazenado."], ["Está disponível em Cochabamba e Santa Cruz?", "Sim. A primeira etapa de validação comercial prioriza instalações piloto em Cochabamba e Santa Cruz, Bolívia."], ["Como posso solicitar um piloto?", "O primeiro passo é entrar em contato pelo WhatsApp para coordenar uma avaliação do local. Essas informações ajudam a determinar se o caso operacional justifica um piloto de 60 a 90 dias."], ["A AgroEscudo substitui a gestão técnica do silo?", "Não. A AgroEscudo não substitui a experiência do operador. Ela fornece dados, alertas, histórico e evidências para apoiar as decisões de gestão."], ["Os sensores são vendidos ou oferecidos como serviço?", "Nesta etapa, a prioridade é o piloto operacional. O modelo final depende do local, da quantidade de nós, do acompanhamento e das necessidades de relatório."], ["Quais operações podem avaliar a AgroEscudo?", "A AgroEscudo foi projetada para operações com grãos armazenados, estoque agrícola, silos, armazéns, plantas, centros de coleta e agroindústrias que precisam de visibilidade e rastreabilidade."]] },
  cta: { eyebrow: "Contato direto", title: "Você armazena grãos e precisa de mais visibilidade?", copy: "Vamos conversar sobre sua instalação, as variáveis críticas e o escopo de um possível piloto.", location: "Cochabamba e Santa Cruz, Bolívia", email: "E-mail" },
  footer: { description: "A AgroEscudo desenvolve tecnologia de monitoramento para reduzir riscos operacionais e pós-colheita em silos, armazéns e centros de coleta de grãos.", navigation: "Navegação", contact: "Contato", location: "Operação inicial em Cochabamba e Santa Cruz, Bolívia.", rights: "Todos os direitos reservados.", tagline: "Monitoramento inteligente para proteger grãos armazenados.", fullPress: "Cobertura completa" },
  whatsapp: "Falar com a AgroEscudo"
};

const qu: typeof es = {
  meta: { title: "AgroEscudo | Silokunapi waqaychasqa granupaq monitoreo", description: "Boliviapi ruwasqa postcosecha monitoreo: IoT sensores, alertas, historial chaymanta reportes silokunapaq, galponkunapaq, acopio wasikunapaq.", ogDescription: "IoT sensores, alertas chaymanta reportes Cochabamba, Santa Cruzpi waqaychasqa granuta qhawarinapaq." },
  nav: { product: "Sistema", how: "Imayna llamk'an", platform: "Plataforma", agrotech: "AgroTECH", progress: "Ñawpaqman risqanchik", ecosystem: "Yanapakuqkuna", press: "Willakuykuna", pilot: "Piloto", login: "Yaykuy", cta: "Piloto mañay", open: "Menú kichariy", close: "Menú wichq'ay", home: "AgroEscudo qallariy" },
  hero: { alt: "Silo chaymanta AgroEscudo monitoreo nodopa conceptual rikch'aynin", eyebrow: "Boliviapi ruwasqa AgTech, postcosecha waqaychanapaq", brand: "AgroEscudo.", title: "Bolivia granupaq digital escudo.", promise: "Granu mana willanchu. AgroEscudoqa willan.", copy: "Silokunapi chaymanta acopio wasikunapi condición importantekunata qhawariyku, riesgo chinkayman mana tukuchkaptin ruwanapaq.", note: "Kayqa conceptual instalaciónmi. Sapa sitioqa wakin configuraciónta munan.", primary: "Piloto mañay", secondary: "Imayna llamk'an", tertiary: "Yaykuy", microcopy: "IoT sensores · Alertas · Historial · Bitácora · Reportes", location: "Cochabamba, Santa Cruzpi pilotokuna wakichisqa.", readings: [["Temperatura", "Sapa kuti ñawirisqa"], ["Humedad", "Umbral churarisqa"], ["Estado", "Nodo tinkisqa"]] },
  capabilities: { aria: "Ruwasqa atiyninkuna", items: [["IoT", "Nodo llamk'achkan"], ["LoRa", "Comunicación yachasqa"], ["Web + Android", "MVP producto"], ["Bolivia", "Cochabamba chaymanta Santa Cruz"]] },
  problem: { eyebrow: "Mana rikukuq riesgo", title: "Problemaqa mana granu chinkaptin qallarinchu.", copy: "Waqaychana ukhupi imapas ruwachkaptin mana pachanpi rikuy atiptinmi qallarin.", support: "Temperatura, humedad chaymanta tendenciaqa evidenciawan decisiónta yanapan.", visual: "Mana rikukuq condiciones. Qhipa decisiones. Mana historial.", signals: [["Temperatura", "Q'uñi tikray"], ["Humedad", "Pachapa condiciónnin"], ["Tendencia", "Riesgopa puriynin"]] },
  solution: { eyebrow: "AgroEscudo sistema", title: "Hunt'a sistema. Mana sapallan sensorchu.", copy: "Nodo variables importantes nisqata qillqan. LoRa comunicación datokunata apachin, plataformañataq historialpi wakichin, equipo qhawanampaq chaymanta qillqanampaq.", items: [["Nodo", "Variables qillqan"], ["LoRa", "Lecturas apachin"], ["Gateway", "Datokuna huñun"], ["Plataforma", "Historial wakichin"], ["Alerta", "Kutichiyta qallarin"]], status: "MVP arquitectura campopi validanapaq ruwasqa.", flow: "Sensor → evidencia → decisión" },
  how: { eyebrow: "Imayna llamk'an", title: "Granumanta alertakama, mana chinkaspa.", steps: [["Churayku", "Nodoqa cheqasman wakichisqa, operadorwan variables akllasqata qillqan."], ["Qhawariyku", "Lecturakuna waqaychasqa chaymanta sapa kuti apachisqa, internet pisi kaptinpas."], ["Alertayku", "Sistemaqa piloto umbralninkunamanta lluqsisqa condiciónkunata tarin."], ["Qillqayku", "Historial, alertas chaymanta acciones qhawanapaq reportekunapipas kanku."]] },
  architecture: { aria: "AgroEscudo arquitectura diagrama", alt: "AgroEscudo sistema diagrama: granu, sondas, LoRa, gateway, API, dashboard chaymanta alertas", caption: "MVP conceptual arquitectura. Sondakuna, tupuna cheqakuna chaymanta conectividad sapa instalaciónman hina akllakun.", labels: { silo: "Silo + granu", probes: "Ukhu sondakuna", node: "SiloSensor", lora: "LoRa local", gateway: "Gateway", gatewayDetail: "Waqaychan, sincronizan", cloud: "Internet + API", cloudDetail: "Datos kachkan", platform: "Dashboard + app", platformDetail: "Alertas · historial · reportes", alert: "Alerta", grain: "Granu temperatura", ambient: "Pacha", connection: "Batería, conexión" }, items: [["SiloSensor", "Akllasqa variables tupun"], ["LoRa", "Cheqapi comunicación"], ["Gateway", "Waqaychan chaymanta sincronizan"], ["Internet + API", "Lecturakuna wakichin"], ["Plataforma", "Alertas, historial chaymanta reportes"]] },
  platform: { eyebrow: "Plataforma ruwasqa", title: "Llapan datos. Huk operación.", copy: "Kunan condiciónkuna, alertakuna, historial chaymanta evidencia operativa, dato mana sensor ukhullapi qhipananpaq.", items: ["Estado general", "Alertas", "Historial", "Reportes"], window: "AgroEscudo plataforma · demostración", alt: "AgroEscudo plataforma, estado, alertas chaymanta indicadoreswan", note: "MVP ruwasqapa captura, demostración datokunawan.", login: "Plataformaman yaykuy", demo: "Demostración mañay" },
  credibility: { press: "La Razónpi rikuchisqa", ecosystem: "Institución yanapay", technology: "IoT MVP ruwasqa", local: "Bolivia tecnología" },
  film: { eyebrow: "AgroEscudo puriy", title: "Silomanta datokama. Datomanta decisiónkama.", copy: "Sensorkunata, comunicaciónta chaymanta plataformata tinkichiq sistemapa rikch'aynin, waqaychana condicionkunata operación willakuyman tukuchinapaq.", note: "Sistemapa chaymanta MVPpa conceptual audiovisual rikch'aynin. Mana comercial instalación nita ruwasqa pilotochu.", controls: "Video kamachina", play: "Videota purichiy", pause: "Videota sayachiy", soundOn: "Uyarinata kichariy", soundOff: "Videota upallachiy", railLabel: "AgroEscudo sistema puriynin", rail: ["SiloSensor", "LoRa local", "Gateway", "API", "Alerta", "Decisión"] },
  product: { eyebrow: "Sistema", title: "Tupuy. Tariy. Ruway.", copy: "Waqaychana señalkunata operación ruwayman tukuchiq hunt'a sistema.", items: [["Monitoreo", "Sitiopaq akllasqa variables sapa kuti ñawirisqa."], ["Alertas", "Condición umbralmanta lluqsiptin willakuy."], ["Historial, bitácora", "Eventokuna chaymanta acciones huk fuentepi."], ["Reportes", "Técnico chaymanta operación qatiypaq evidencia."]] },
  why: { eyebrow: "Imarayku AgroEscudo", title: "Boliviapa chiqaq operaciónninpaq ruwasqa.", items: [["Local tecnología", "Bolivia waqaychana chaymanta postcosecha realidadninman asuykusqa."], ["Internet pisi kaptin", "Conexión kutimuptin lecturakuna waqaychaspa sincronizan."], ["B2B enfoque", "Inventario, calidad chaymanta operación equipokunapaq ruwasqa."]] },
  agrotech: {
    eyebrow: "AgroTECH Bolivia 2026", title: "AgroEscudoqa postcosecha waqaychayta AgroTECH escenarioman aparqa.", copy: "Brayan Javier Mejía Saavedra chaymanta equipoqa agricultura sectorpa runakunaman sistemata rikuchirqanku, riesguta, variables importantes chaymanta sensormanta decisiónkama puriyninta sut'inchaspa.", date: "28, 29 julio 2026", location: "Santa Cruz · Bolivia", link: "Público reconocimientota qhaway", videoTitle: "AgroEscudo escenariopi", videoCaption: "Monitoreo, ñawpaq alerta chaymanta waqaychasqa granu waqaychaymanta chiqaq video.", teamLabel: "AgroEscudo equipo", teamAlt: "AgroEscudo equipo AgroTECH Bolivia 2026 standpi", teamCaption: "Equipo chaymanta prototipokuna AgroEscudo standpi rikuchisqa.", galleryLabel: "Eventopa rikch'ayninkuna", galleryCopy: "Escenario, arquitectura, stand chaymanta sectorwan tinkuy.", open: "Rikch'ayninta hatunyachiy", close: "Galeríata wichq'ay", previous: "Ñawpaq rikch'ay", next: "Qatiq rikch'ay", items: [["AgroTECH Bolivia 2026 auditorio técnico presentaciónpi", "AgroTECHqa agricultura chaymanta innovación runakunata huñurqa."], ["AgroEscudo equipo postcosecha riesguta escenariopi sut'inchachkan", "Postcosecha problemaqa evento runakunaman sut'inchasqa."], ["SiloSensor, gateway, plataforma, alerta chaymanta acción puriynin", "AgroEscudo arquitectura, sensormanta decisiónkama."], ["AgroEscudo sistema standkunapi rikuchisqa", "Técnico rimaykuna chaymanta sistema demostración standpi."], ["AgroTECH Bolivia 2026 participantes chaymanta organizaciones", "Agricultura, innovación ecosistemawan tinkuy."]]
  },
  progress: { eyebrow: "Rikuchiy atina ñawpaqman risqa", title: "Prototipomanta piloto operaciónkama.", copy: "Sapa componentepa kunan estado-ninta chiqaqta rikuchiyku. Qatiq pruebaqa ruwasqa tecnologíata waqaychana cheqapi tinkichiymi.", items: [["Nodo chaymanta LoRa comunicación", "Laboratoriopi yachasqa"], ["API chaymanta lecturas waqaychay", "Ruwasqa"], ["Web dashboard", "Publicasqa"], ["Android aplicación", "MVP versión"], ["Mana conexión kaptin kutichiy", "Validaciónpi"], ["Operación realpi churay", "Qatiq piloto"]] },
  founder: { role: "Fundador chaymanta CEO", location: "Cochabamba · Bolivia", alt: "Brayan Javier Mejía Saavedra, AgroEscudopa fundador chaymanta CEO", lead: "AgroEscudota ruwan chaymanta validan, IoT tecnologíata waqaychana postcosecha necesitadkunawan tinkichispa.", copy: "Paypa llamk'ayninqa producto yuyayta, tecnología ruwayta chaymanta pilotokuna wakichiyta huñun, silo galpón datokunata pachanpi decisiónman tukuchinapaq.", principle: "Llamk'ana kamachi", quote: "Allin tecnología, evidencia operativa chaymanta campopi validación.", contact: "Brayanwan rimay", interview: "La Razón entrevistata ñawiriy" },
  ecosystem: { eyebrowTop: "Institución yanapakuqkuna", headline: "Bolivia innovaciónta wiñachiq organizacioneswan yanapasqa.", eyebrow: "Yanapawaqniyku organizaciones", title: "Aswan allinta purinapaq chiqaq yanapay.", copy: "AgroEscudo tecnología, negocio chaymanta academia wiñayninta Bolivia organizacioneswan kallpachan; paykuna innovación, incubación chaymanta formación técnicawan llamk'anku.", categories: ["Preaceleración", "Tecnología incubación", "Academia yanapay", "Técnico yanapay"], descriptions: ["Negociota kallpachay chaymanta mercadoman yaykunapaq wakichiy.", "Innovación ecosistemapi chaymanta preaceleraciónpi tinkichiy.", "Innova Up empresata kallpachana procesopi institución yanapay.", "Tecnología empresata wakichiy, incubay chaymanta wiñachiy.", "Fundador equipopa tecnología ruwananpaq academia yanapay.", "EMBATEwan chaymanta proyectopa técnico articulaciónninwan tinkisqa academia.", "Agricultura sectorpi validación aplicada kallpachanapaq técnico articulación."], disclaimer: "Kay yanapayqa acompañamiento, incubación, preaceleración chaymanta institución articulación procesokunamanta; mana inversión, certificación nita comercial relación niyku." },
  clients: { eyebrow: "Pipaq", title: "Qhipata yachayqa aswan achkha chanin operacionespaq.", riskLabel: "Operación riesgo", decisionLabel: "Allin decisión", items: [["Inventario waqaychay", "Silos · galpones · acopio wasikuna", "Huñusqa inventarioqa tikrakuykunaman kichasqa, wakin kuti qhawasqalla mana rikunmanchu.", "Evidenciwan inspección, ventilación utaq qatiyta ñawpaqman churay."], ["Operación mana sayanapaq", "Molinos · alimentos balanceados · agroindustria", "Umbralmanta lluqsisqa condiciónqa recepción, almacenamiento chaymanta planta programaciónta wakllichinman.", "Qatiq proceso mana wakllichkaptin kutichiyta wakichiy."], ["Qhawariy chaymanta trazabilidad", "Cooperativas · calidad · achkha sitio kamachiqkuna", "Huk historial mana kaptin, sitiokunata tupachiy chaymanta acciones sut'inchay pacha apakun.", "Eventokunata, responsables chaymanta acciones huk fuentemanta qhaway."]] },
  press: { eyebrow: "Willakuy, reconocimiento chaymanta cobertura", title: "AgroEscudo innovación ukhupi.", copy: "Boliviapi ruwasqa tecnología postcosecha riesguta pisiyachinapaq silokunata, galponkunata chaymanta acopio wasikunata qhawarisqan manta willakuykuna.", cover: "Suplementopa portada", article: "Publicasqa entrevista", evidence: "Prensa evidencia", sourceNote: "Qallariy fuentepi publicaciónta qhaway.", open: "Fuente qhaway", more: "AgroEscudomanta aswan willakuy", moreCopy: "Prensa, reconocimiento chaymanta participación; mana clientes, inversión nita certificaciónchu.", moreLink: "Prensa p'anqata qhaway", readAria: "AgroEscudo coberturata kaypi ñawiriy" },
  pilot: { eyebrow: "Qatiq piloto", title: "Qampa instalaciónniyki AgroEscudopa qatiq piloton kanman.", copy: "Cochabamba, Santa Cruzpi almacenamiento, acopio chaymanta transformación operaciones mask'ayku, sistema real condiciónkunapi validanapaq chaymanta disponibilidad, eventokuna, kutichiy pacha tupunapaq.", location: "Cochabamba · Santa Cruz", primary: "Sitio evaluación mañay", secondary: "WhatsAppwan rimay", note: "Evaluaciónqa kay casoq operacionpaq allin kasqanta qhawan. Mana gratuito piloto nita ranti compromisochu.", route: "Validación ñan", stages: ["Sitio qallariy evaluación", "Variables chaymanta umbrales akllay", "Churay chaymanta monitoreo", "Resultados reporte"], observe: "Imata qhawasqa", metrics: ["Sistema disponibilidad", "Taripasqa eventokuna", "Kutichiy pacha", "Qillqasqa acciones"] },
  faq: { eyebrow: "Sapa kuti tapuykuna", title: "AgroEscudota qhawanapaq yachanapaq.", copy: "Boliviapi silo monitoreo, waqaychasqa granu chaymanta IoT agrícola qhawachkaq operadorespaq sut'i kutichiykuna.", items: [["¿Imata AgroEscudo qhawarin?", "AgroEscudo silokunapi, galponkunapi, acopio wasikunapi temperatura chaymanta humedadta qhawarin, postcosecha riesgo condiciónkunata tarinapaq chaymanta decisiónta yanapanapaq."], ["¿Internet sapa kuti mana kaptin AgroEscudo llamk'anchu?", "Pilotoqa internet tikrakuq kasqanman hina ruwasqa. Arquitecturaqa campopi llamk'ayta chaymanta lecturakuna qatiyta yuyarin, allin conexiónllamanta mana hap'ipakunachu."], ["¿Maypi churakunman?", "Silokunapi, galponkunapi, acopio wasikunapi, molinospi, cooperativakunapi chaymanta agroindustriakunapi qhawakunman."], ["¿Cochabamba, Santa Cruzpi kachkanchu?", "Arí. Qallariy validación comercialqa Cochabamba, Santa Cruzpi piloto instalaciones ñawpaqman churan."], ["¿Imayna piloto mañakun?", "Ñawpaqta WhatsAppwan qillqay, sitio qhawariyta wakichinapaq. Chay willakuywan casoq piloto merecen chayta akllakun."], ["¿AgroEscudo silo técnico manejota qhechunchu?", "Mana. AgroEscudoqa operadorpa yachayninta mana qhechunchu. Datos, alertas, historial chaymanta evidenciawan decisiónta yanapan."], ["¿Sensores rantikunchu utaq serviciopi qukunchu?", "Kunanqa piloto operativo ñawpaqpi kachkan. Modeloqa sitio, nodokuna, acompañamiento chaymanta reportes necesitadman hina akllakun."], ["¿Ima operaciones AgroEscudota qhawankuman?", "Waqaychasqa granuyuq, siloyuq, galponniyuq, plantayuq, acopio wasiyuq chaymanta agroindustria operacionespaq ruwasqa."]] },
  cta: { eyebrow: "Chiqaq contacto", title: "Waqaychasqa granuyki kachkanchu, aswan rikuyta munankichu?", copy: "Sitioymanta, variables importantesmanta chaymanta posible pilotomanta rimasun.", location: "Cochabamba chaymanta Santa Cruz, Bolivia", email: "Correo" },
  footer: { description: "AgroEscudo silokunapi, galponkunapi, acopio wasikunapi riesgo operativo chaymanta postcosecha pisiyachinapaq monitoreo tecnologíata ruwan.", navigation: "Navegación", contact: "Contacto", location: "Qallariy operación Cochabamba, Santa Cruz, Boliviapi.", rights: "Llapan derechokuna waqaychasqa.", tagline: "Waqaychasqa granuta waqaychanapaq monitoreo inteligente.", fullPress: "Llapan cobertura" },
  whatsapp: "AgroEscudowan rimay"
};

export const messages: Record<Locale, typeof es> = { "es-BO": es, en, "pt-BR": pt, "qu-BO": qu };

export function getMessages(locale: Locale) {
  return messages[locale];
}

const contactCopy: Record<Locale, { whatsapp: string; visit: string; emailSubject: string }> = {
  "es-BO": {
    whatsapp: "Hola, conocí AgroEscudo mediante su página web. Me interesa conocer el sistema de monitoreo para silos o almacenamiento de granos y coordinar una demostración.",
    visit: "Hola AgroEscudo, quiero agendar una evaluación técnica del sitio.",
    emailSubject: "Solicitud de piloto AgroEscudo"
  },
  en: {
    whatsapp: "Hello AgroEscudo, I found you through your website. I would like to learn about the monitoring system for silos and stored grain and schedule a demonstration.",
    visit: "Hello AgroEscudo, I would like to schedule a technical site assessment.",
    emailSubject: "AgroEscudo pilot request"
  },
  "pt-BR": {
    whatsapp: "Olá, conheci a AgroEscudo pelo site. Quero conhecer o sistema de monitoramento para silos e grãos armazenados e agendar uma demonstração.",
    visit: "Olá AgroEscudo, quero agendar uma avaliação técnica do local.",
    emailSubject: "Solicitação de piloto AgroEscudo"
  },
  "qu-BO": {
    whatsapp: "Hola AgroEscudo, página webniykichikpi riqsiyki. Silokunapaq monitoreo sistemata riqsiyta chaymanta demostraciónta wakichiyta munani.",
    visit: "Hola AgroEscudo, sitio técnico evaluaciónta wakichiyta munani.",
    emailSubject: "AgroEscudo piloto mañakuy"
  }
};

export function getContactLinks(locale: Locale) {
  const copy = contactCopy[locale];
  return {
    whatsapp: `https://wa.me/59179366846?text=${encodeURIComponent(copy.whatsapp)}`,
    technicalVisit: `https://wa.me/59179366846?text=${encodeURIComponent(copy.visit)}`,
    email: `mailto:agroescudo@gmail.com?subject=${encodeURIComponent(copy.emailSubject)}`
  };
}

export function getLocaleMetadata(locale: Locale): Metadata {
  const content = messages[locale].meta;
  const route = localeRoutes[locale];
  return {
    title: content.title,
    description: content.description,
    keywords: [...siteConfig.keywords],
    alternates: {
      canonical: route,
      languages: {
        "es-BO": "/",
        en: "/en",
        "pt-BR": "/pt",
        "qu-BO": "/qu",
        "x-default": "/"
      }
    },
    openGraph: {
      title: content.title,
      description: content.ogDescription,
      url: absoluteUrl(route),
      siteName: siteConfig.name,
      locale: locale.replace("-", "_"),
      alternateLocale: locales.filter((item) => item !== locale).map((item) => item.replace("-", "_")),
      type: "website",
      images: [{ url: absoluteUrl(siteConfig.ogImage), width: 1200, height: 630, alt: content.title }]
    },
    twitter: { card: "summary_large_image", title: content.title, description: content.ogDescription, images: [absoluteUrl(siteConfig.ogImage)] }
  };
}
